# Projects, R Markdown, and Data Wrangling

## Intended Learning Outcomes {.unnumbered}

By the end of this chapter you should be able to:

-   Re-familiarise yourself with setting up projects
-   Re-familiarise yourself with RMarkdown documents
-   Recap and apply data wrangling procedures to analyse data

## [Individual Walkthrough]{style="color: #EBA347; text-transform: uppercase;"} {.unnumbered}

## R and R Studio

Remember, R is a programming language that you will write code in and RStudio is an Integrated Development Environment (IDE) which makes working with R easier as it's more user friendly. You need both components for this course. 

If this is not ringing any bells yet, have a quick browse through the [materials from year 1](https://psyteachr.github.io/data-skills-v2/sec-intro.html?q=RMark#sec-intro-r){target="_blank"}to refresh yopur memory.

### R server

R and RStudio are already installed on the *R server*. We recommend using the server if your computer does not allow installation (e.g., a Chromebook), or if you have problems with installing R on your computer. Otherwise, you should consider installing R and RStudio on your own computer.

You will find the link to the server on Moodle.

### Installing R and RStudio on your computer

@sec-installing-r has detailed instructions on how to install R and RStudio on your own computer. There are also some links to a series of walkthroughs for installing R on different types of computers/ operating systems.

If you had R and RStudio installed on your own computer last year, we recommend updating to the latest versions. In fact, it might be good to do that at the start of each academic year. Detailed guidance can be found in @sec-updating-r.

Once you have installed R and RStudio, come back to this chapter. 


## Activity 1: Creating a new project

It's important that we create projects every time we start a new project. It makes life easier in terms of folder locations and working directories, basically keeping all the data and the RMarkdown documents in one location.

Last year, you learnt how to create projects on the server, so you already know the steps. If cannot quite recall how that was done, go back to the [Level 1 materials](https://psyteachr.github.io/data-skills-v2/sec-intro.html?q=RMark#new-project){target="_blank"}.


Now we are moving on to setting up projects on the computer.



## R Markdown basics

### Creating an R Markdown file

delete everything after the knitting part from line 12

and save it in the project. All of the data files you need, should go into the same project folder too

### Code Chunks vs Text

### Knitting

## Data Wrangling

The basic ones are the **Wickham 6** that you've encountered already last year

table of the Wickham 6 refer them back to the different chapters where they encountered it in level 1

| Function    | Description                                                | Chapter                        |
|:-----------------|:----------------------------------|:------------------|
| select()    | Include or exclude certain variables (columns)             | add links to final L1 chapters |
| filter()    | Include or exclude certain observations/data (rows)        |                                |
| mutate()    | Creates new variables (columns)                            |                                |
| arrange()   | Changes the order of observations (rows)                   |                                |
| group_by()  | Organises the observations (rows) into groups              |                                |
| summarise() | Create summary variables for groups of observations (rows) |                                |

### Brief recap of the Wickham 6

#### select

Massive dataframes use a lot of computing power - to reduce that, it would be worth focussing on the columns you need

selecting variables - you can rename them too if you don't like the column name as is

if you wanna rename something at a later stage, use rename. Works in the same manner as select as in new name = old name. --\> This could be in an information box

deselecting deselecting multiple variables

#### filter

text - one condition vs more than one condition numbers - smaller/ larger

#### arrange

ascending, descending - NAs will always listed at the end regardless

#### mutate

Allison's drawing

#### group_by & summarise

## Other useful functions

### count

### joining things together from separate datasets

**inner_join**

**full_join**

Use the 2 chopped up tables earlier and merge them. They have no values overlapping, so it's difficult

## Tidy data

### pivoting data

pivot_wider and pivot_longer

### recode

### case_when

Allison's drawing

## [Pair-coding in the lab]{style="color: #EBA347; text-transform: uppercase;"} {.unnumbered}

## [Test your knowledge and challenge yourself]{style="color: #EBA347; text-transform: uppercase;"} {.unnumbered}

or for the Wickham 6 part, we could just go here is some data, lets apply them all.

Activity 1: selecting specific columns First of all, we want to select the relevant columns
