# Revisiting probability and introduction to NHST 

## Intended Learning Outcomes {.unnumbered}

By the end of this chapter you should be able to:


## [Individual Walkthrough]{style="color: #EBA347; text-transform: uppercase;"} {.unnumbered}


## Overview

Which test to use depends on what type of variable you have and what your research question is about.


* 2 categorical: Chi^2 test
* 1 continuous: one-sample t-test
* 1 continuous and 1 categorical: independent or paired t-test (depending if within or between)
* 2 continuous: correlation or regression

Maybe in a flow chart


## Activity 1: Setup

* create a new project
* create a new Rmd file and save it to your project folder
* delete everything after the setup code chunk 



## Activity 2: Download the data

* Download the data: link
* Talk about the files
* insert citation and abstract of the data
* Look at the codebook and the variables






## recap of probability

go back chapter 1


## Null-hypothesis testing



## Binomial test

is used when your variable is categorical

## One-sample t-test

is used with a continuous variable

