# One-way ANOVA {#sec-oneway}

## Intended Learning Outcomes {.unnumbered}

By the end of this chapter you should be able to:

- Apply and interpret a one-way ANOVA.
- Break down the results of a one-way ANOVA using post-hocs tests and apply a correction for multiple comparisons.
- Conduct a power analysis for a one-way ANOVA.

## [Individual Walkthrough]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}

## Activity 1: Setup

* Open last week’s project
* Create a new `.Rmd` file and save it to your project folder
* Delete everything after the setup code chunk (e.g., line 12 and below)

$\rightarrow$


## Activity 2: Download the data

* Download the data: link
* Talk about the files
* insert citation and abstract of the data
* Look at the codebook and the variables



Kruskal-Wallis test: This is equivalent to the global significance test in a one-way ANOVA—it tests for differences between the central tendency of several samples.



## [Pair-coding]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}




## [Test your knowledge]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}


