# Factorial ANOVA {#sec-factorial}

## Intended Learning Outcomes {.unnumbered}

By the end of this chapter you should be able to:
- Apply and interpret a factorial ANOVA.
- Break down the results of a factorial ANOVA using post-hocs tests and apply a correction for multiple comparisons.
- Check statistical assumptions for factorial ANOVA through your understanding of the design and diagnostic plots.
- Visualise the results of a factorial ANOVA through an interaction plot.


## [Individual Walkthrough]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}

## Activity 1: Setup

* create a new project
* create a new Rmd file and save it to your project folder
* delete everything after the setup code chunk 



## Activity 2: Download the data

* Download the data: link
* Talk about the files
* insert citation and abstract of the data
* Look at the codebook and the variables




## [Pair-coding]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}

::: {.callout-important}

This week's pair-coding activity mirrors the one from @sec-within (Semester 1). While there is no lab scheduled this week, I wanted to provide an opportunity for you to practice. You can treat this either as a "Challenge Yourself" activity or get together with friends to work through it together.

:::


## [Test your knowledge]{style="color: #F39C12; text-transform: uppercase;"} {.unnumbered}

#### Question 1 {.unnumbered}

**A researcher wants to compare memory test scores across three different age groups (young adults, middle-aged adults, and older adults). What type of ANOVA should they use?**

`r longmcq(sample(c( answer = "One-way between-subjects ANOVA", x = "One-way repeated-measures ANOVA", x = "Factorial ANOVA", x = "Mixed-design ANOVA" )))`

::: {.callout-caution collapse="true" icon="false"}

## Explain this answer

Correct Answer:

A **one-way between-subjects ANOVA** is appropriate because there is one independent variable (age group) with three levels, and each participant is only tested in one group.

Incorrect Answers:

* A repeated-measures ANOVA is incorrect because it is used when the same participants are measured multiple times.
* A factorial ANOVA is incorrect because it is used when there are two or more independent variables.
* A mixed-design ANOVA is incorrect because it is used when there is at least one between-subjects factor and one within-subjects factor.

:::

