lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
book:
  title: Analysis
  subtitle: ''
  author:
    orcid: 0000-0002-2135-6888
    name:
      family: Mahrholz
      given: Gaby
    roles: ~
  doi: ''
  license: CC-BY
  description: Level 2 UG Analysis book
  cover-image: images/logos/logo_analysis.png
  image: images/logos/logo_analysis.png
  favicon: images/logos/logo_analysis.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2024) Gaby Mahrholz
  chapters:
  - index.qmd
  - 01-basics.qmd
  - 02-wrangling.qmd
  - 03-dataviz.qmd
  - 04-dataviz2.qmd
  - 05-chi-square-one-sample.qmd
  - 06-independent.qmd
  - 07-paired.qmd
  - 08-correlation.qmd
  - 09-simple-regression.qmd
  - 10-multiple-regression.qmd
  - 11-one-way-anova.qmd
  - 12-factorial-anova.qmd
  appendices:
  - appendix-a-installing-r.qmd
  - appendix-b-updating-packages.qmd
  - appendix-c-exporting-server.qmd
  - appendix-d-symbols.qmd
  - appendix-x-How-to-cite-R.qmd
  - appendix-y-license.qmd
  - references.qmd
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    - include/custom.scss
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
