---
title: "Untitled"
author: "GM"
date: "2024-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library and data

```{r}
library(tidyverse)
data_prp <- read_csv("PRP_Data_reduced.csv")
```
I need to reverse-code the reverse-coding for the SAT

```{r}
sat_qs <- data_prp %>% 
  select(Code, starts_with("SATS")) %>% 
  pivot_longer(cols = -Code, names_to = "Items", values_to = "Scores") %>% 
  mutate(Scores_corrected = case_when(
    str_detect(Items, "_R") ~ 8-Scores,
    .default = Scores
  )) %>% 
  select(-Scores) %>% 
  pivot_wider(names_from = Items, values_from = Scores_corrected)


data_prp_new <- data_prp %>% 
  select(-starts_with("SATS")) %>% 
  full_join(sat_qs) %>% 
  select(Code:Plan_prereg, SATS28_1_Affect_F_Time1:SATS28_28_Difficulty_R_Time1, QRPs_1_Time1:Included_prereg_18, SATS28_1_Affect_F_Time2:SATS28_28_Difficulty_R_Time2, QRPs_1_Time2:Supervisor_15_R)

write_csv(data_prp_new, "data_prp_ch1.csv")
```


4. list item 4
    1) this item needs 4 spaces for the indent
        1) this item needs another 4 spaces from the previous one
6. item 6
    a) sub-item labelled "a)"
    i) sub-item labelled "i)"
        C) sub-item labelled "C)"
        Z) sub-item labelled "Z)"
5. item 5

## corrected data

```{r}
data_qrps <-read_csv("prp_data_reduced_ch1.csv") %>% 
  select(Code, QRPs_1_Time1:QRPs_11_Time1) %>% 
  pivot_longer(cols = -Code, names_to = "names", values_to = "values") %>% 
  group_by(Code) %>% 
  summarise(QRP_mean_Time1 = mean(values))
```

