<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Level 2 UG Analysis book">
<title>Analysis - 6&nbsp; Chi-square and one-sample t-test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-independent.html" rel="next">
<link href="./05-dataviz2.html" rel="prev">
<link href="./images/logos/logo_analysis.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
<link rel="stylesheet" href="include/custom.scss">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-chi-square-one-sample.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analysis</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Projects and R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data wrangling I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data wrangling II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data viz I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-dataviz2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-chi-square-one-sample.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-independent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-paired.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Paired t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-one-way-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-updating-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Updating R, RStudio, and packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-c-exporting-server.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Exporting files from the server</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-d-symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Symbols</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-x-How-to-cite-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Citing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-y-license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#intended-learning-outcomes" id="toc-intended-learning-outcomes" class="nav-link active" data-scroll-target="#intended-learning-outcomes">Intended Learning Outcomes</a></li>
  <li><a href="#individual-walkthrough" id="toc-individual-walkthrough" class="nav-link" data-scroll-target="#individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">6.1</span> Overview</a></li>
  <li><a href="#activity-1-setup-download-the-data" id="toc-activity-1-setup-download-the-data" class="nav-link" data-scroll-target="#activity-1-setup-download-the-data"><span class="header-section-number">6.2</span> Activity 1: Setup &amp; download the data</a></li>
  <li><a href="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" id="toc-activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="nav-link" data-scroll-target="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data"><span class="header-section-number">6.3</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</a></li>
  <li><a href="#activity-3-data-wrangling" id="toc-activity-3-data-wrangling" class="nav-link" data-scroll-target="#activity-3-data-wrangling"><span class="header-section-number">6.4</span> Activity 3: Data wrangling</a></li>
  <li>
<a href="#sec-chi_square" id="toc-sec-chi_square" class="nav-link" data-scroll-target="#sec-chi_square"><span class="header-section-number">6.5</span> Activity 4: Cross-tabulation Chi-square test</a>
  <ul class="collapse">
<li><a href="#task-1-preparing-the-dataframe" id="toc-task-1-preparing-the-dataframe" class="nav-link" data-scroll-target="#task-1-preparing-the-dataframe"><span class="header-section-number">6.5.1</span> Task 1: Preparing the dataframe</a></li>
  <li><a href="#task-2-compute-descriptives" id="toc-task-2-compute-descriptives" class="nav-link" data-scroll-target="#task-2-compute-descriptives"><span class="header-section-number">6.5.2</span> Task 2: Compute descriptives</a></li>
  <li><a href="#task-3-check-assumptions" id="toc-task-3-check-assumptions" class="nav-link" data-scroll-target="#task-3-check-assumptions"><span class="header-section-number">6.5.3</span> Task 3: Check assumptions</a></li>
  <li><a href="#task-4-create-an-appropriate-plot" id="toc-task-4-create-an-appropriate-plot" class="nav-link" data-scroll-target="#task-4-create-an-appropriate-plot"><span class="header-section-number">6.5.4</span> Task 4: Create an appropriate plot</a></li>
  <li><a href="#task-5-compute-a-chi-square-test" id="toc-task-5-compute-a-chi-square-test" class="nav-link" data-scroll-target="#task-5-compute-a-chi-square-test"><span class="header-section-number">6.5.5</span> Task 5: Compute a chi-square test</a></li>
  <li><a href="#task-6-the-write-up" id="toc-task-6-the-write-up" class="nav-link" data-scroll-target="#task-6-the-write-up"><span class="header-section-number">6.5.6</span> Task 6: The write-up</a></li>
  </ul>
</li>
  <li>
<a href="#sec-onesample" id="toc-sec-onesample" class="nav-link" data-scroll-target="#sec-onesample"><span class="header-section-number">6.6</span> Activity 5: One-sample t-test</a>
  <ul class="collapse">
<li><a href="#task-1-preparing-the-dataframe-1" id="toc-task-1-preparing-the-dataframe-1" class="nav-link" data-scroll-target="#task-1-preparing-the-dataframe-1"><span class="header-section-number">6.6.1</span> Task 1: Preparing the dataframe</a></li>
  <li><a href="#task-2-compute-descriptives-1" id="toc-task-2-compute-descriptives-1" class="nav-link" data-scroll-target="#task-2-compute-descriptives-1"><span class="header-section-number">6.6.2</span> Task 2: Compute descriptives</a></li>
  <li><a href="#task-3-create-an-appropriate-plot" id="toc-task-3-create-an-appropriate-plot" class="nav-link" data-scroll-target="#task-3-create-an-appropriate-plot"><span class="header-section-number">6.6.3</span> Task 3: Create an appropriate plot</a></li>
  <li><a href="#task-4-check-assumptions" id="toc-task-4-check-assumptions" class="nav-link" data-scroll-target="#task-4-check-assumptions"><span class="header-section-number">6.6.4</span> Task 4: Check assumptions</a></li>
  <li><a href="#task-5-compute-a-one-sample-t-test-and-effect-size" id="toc-task-5-compute-a-one-sample-t-test-and-effect-size" class="nav-link" data-scroll-target="#task-5-compute-a-one-sample-t-test-and-effect-size"><span class="header-section-number">6.6.5</span> Task 5: Compute a One-sample t-test and effect size</a></li>
  <li><a href="#task-6-sensitivity-power-analysis" id="toc-task-6-sensitivity-power-analysis" class="nav-link" data-scroll-target="#task-6-sensitivity-power-analysis"><span class="header-section-number">6.6.6</span> Task 6: Sensitivity power analysis</a></li>
  <li><a href="#task-7-the-write-up" id="toc-task-7-the-write-up" class="nav-link" data-scroll-target="#task-7-the-write-up"><span class="header-section-number">6.6.7</span> Task 7: The write-up</a></li>
  </ul>
</li>
  <li><a href="#sec-alternative_one_sample" id="toc-sec-alternative_one_sample" class="nav-link" data-scroll-target="#sec-alternative_one_sample"><span class="header-section-number">6.7</span> Activity 6: Non-parametric alternative</a></li>
  <li><a href="#pair-coding" id="toc-pair-coding" class="nav-link" data-scroll-target="#pair-coding"><span style="color: #F39C12; text-transform: uppercase;">Pair-coding</span></a></li>
  <li><a href="#test-your-knowledge-on-chapters-3-and-4" id="toc-test-your-knowledge-on-chapters-3-and-4" class="nav-link" data-scroll-target="#test-your-knowledge-on-chapters-3-and-4"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge on Chapters 3 and 4</span></a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-nhstI" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="intended-learning-outcomes" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="intended-learning-outcomes">Intended Learning Outcomes</h2>
<p>By the end of this chapter you should be able to:</p>
<ul>
<li>compute a Cross-tabulation Chi-square test and report the results</li>
<li>compute a one-sample t-test and report the results</li>
<li>understand when to use a non-parametric equivalent for the one-sample t-test, compute it, and report the results</li>
</ul></section><section id="individual-walkthrough" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></h2>
</section><section id="overview" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="overview">
<span class="header-section-number">6.1</span> Overview</h2>
<p>Which test to use depends on what type of variable(s) you have and what your research question is about. You can see them in the flowchart below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/Flowchart_tests_drawio.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Simplified flowchart to help select the most appropriate test (created with <a href="https://draw.io/" target="_blank">drawio</a>). <a href="images/Flowchart_tests_drawio.png" target="_blank">View larger version</a></figcaption></figure>
</div>
<p>You can see below in which chapter they will be discussed:</p>
<ul>
<li>Cross-tabulation chi-Square test (this chapter, <a href="#sec-chi_square"><span>Section&nbsp;6.5</span></a>)</li>
<li>One-sample t-test (this chapter, <a href="#sec-onesample"><span>Section&nbsp;6.6</span></a>)</li>
<li>Two-sample or independent t-test (between-subjects design, <a href="07-independent.html"><span>Chapter&nbsp;7</span></a>)</li>
<li>Paired t-test (within-subjects design, <a href="08-paired.html"><span>Chapter&nbsp;8</span></a>)</li>
<li>Correlation (<a href="09-correlation.html"><span>Chapter&nbsp;9</span></a>)</li>
<li>Simple regression (<a href="10-regression.html"><span>Chapter&nbsp;10</span></a>)</li>
<li>Multiple regression (<a href="11-multiple-regression.html"><span>Chapter&nbsp;11</span></a>)</li>
<li>One-way ANOVA (<a href="12-one-way-anova.html"><span>Chapter&nbsp;12</span></a>)</li>
<li>Factorial ANOVA (<a href="13-factorial-anova.html"><span>Chapter&nbsp;13</span></a>)</li>
</ul></section><section id="activity-1-setup-download-the-data" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="activity-1-setup-download-the-data">
<span class="header-section-number">6.2</span> Activity 1: Setup &amp; download the data</h2>
<ul>
<li>create a new project and name it something meaningful (e.g., “2A_chapter6”, or “06_chi_square_one_sample_t”). See <a href="01-basics.html#sec-project"><span>Section&nbsp;1.2</span></a> if you need some guidance.</li>
<li>create a new Rmd file and save it to your project folder. See <a href="01-basics.html#sec-rmd"><span>Section&nbsp;1.3</span></a> if you get stuck.</li>
<li>delete everything after the setup code chunk (e.g., line 12 and below)</li>
<li>download a reduced dataset here: <a href="data/data_ch6.zip" title="download">data_ch6.zip</a>. You’ll see one csv file with demographic information and questionnaire data as well as the codebook.</li>
<li>Extract the data files from the zip folder and place them in your project folder. If you need help, see <a href="01-basics.html#sec-download_data_ch1"><span>Section&nbsp;1.4</span></a>.</li>
</ul>
<p><strong>Citation</strong></p>
<blockquote class="blockquote">
<p>Ballou, N., Vuorre, M., Hakman, T., Magnusson, K., &amp; Przybylski, A. K. (2024, July 12). Perceived value of video games, but not hours played, predicts mental well-being in adult Nintendo players. <a href="https://doi.org/10.31234/osf.io/3srcw" target="_blank">https://doi.org/10.31234/osf.io/3srcw</a></p>
</blockquote>
<p>As you can see, the study is a pre-print published on PsyArXiv Preprints. The data and supplementary materials are available on OSF: <a href="https://osf.io/6xkdg/" target="_blank">https://osf.io/6xkdg/</a></p>
<p><strong>Abstract</strong></p>
<blockquote class="blockquote">
<p>Studies on video games and well-being often rely on self-report measures or data from a single game. Here, we study how 703 US adults’ time spent playing for over 140,000 hours across 150 Nintendo Switch games relates to their life satisfaction, affect, depressive symptoms, and general mental well-being. We replicate previous findings that playtime over the past two weeks does not predict well-being, and extend these findings to a wider range of timescales (one hour to one year). Results suggest that relationships, if present, dissipate within two hours of gameplay. Our non-causal findings suggest substantial confounding would be needed to shift a meaningful true effect to the observed null. Although playtime was not related to well-being, players’ assessments of the value of game time—so called gaming life fit—was. Results emphasise the importance of defining the gaming population of interest, collecting data from more than one game, and focusing on how players integrate gaming into their lives rather than the amount of time spent.</p>
</blockquote>
<p><strong>Changes made to the dataset</strong></p>
<ul>
<li>We selected demographic variables, such as age, gender, ethnicity, employment, education level, and the Warwick-Edinburgh Mental Wellbeing Scale from the rich dataset.</li>
<li>We removed rows with missing values and categorical groupings for which observed frequencies were considered too small for the purpose of this chapter.</li>
<li>We won’t be looking into any game-related associations, but feel free to download the full dataset to explore further.</li>
<li>The original authors had quite strict inclusion criteria for their analysis. We did not, hence we ended up with more participants than the original study</li>
</ul></section><section id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data">
<span class="header-section-number">6.3</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</h2>
<p>Today, we’ll need the following packages <code>tidyverse</code>, <code>lsr</code>, <code>scales</code>, <code>qqplotr</code>, <code>car</code>, <code>pwr</code>, and <code>rcompanion</code> as well as the data <code>data_ballou_reduced</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># load in the packages</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>???</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># read in the data</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>data_ballou <span class="ot">&lt;-</span> ???</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># load in the packages</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(lsr)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(scales)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">library</span>(car)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">library</span>(pwr)</span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="fu">library</span>(rcompanion)</span>
<span id="cb2-9"><a href="#cb2-9"></a></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="co"># read in the data</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>data_ballou <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_ballou_reduced.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="activity-3-data-wrangling" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="activity-3-data-wrangling">
<span class="header-section-number">6.4</span> Activity 3: Data wrangling</h2>
<p>The categorical variables look quite tidy, but we need to <strong>convert gender and education level into factors</strong>. Our statistical test requires factors and categories might be sorted more easily when plotting.</p>
<p>We also have to <strong>calculate the overall score for the Warwick-Edinburgh Mental Wellbeing Scale</strong>. According to the <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official WEMWBS website</a>, the scores of the individual items are summed up.</p>
<ul>
<li>create a new data object <code>data_wemwbs</code> to calculate the summed up scores for the wemwbs.</li>
<li>convert gender and education level into factors in the original <code>data_ballou</code> object. Feel free to sort them in a meaningful order.</li>
<li>join this <code>data_ballou</code> with <code>data_wembs</code>.</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>We converted categorical variables into factors in <a href="04-dataviz.html"><span>Chapter&nbsp;4</span></a> if you need a refresher</li>
<li>Check the <code>QRPs</code> questionnaire in <a href="02-wrangling.html"><span>Chapter&nbsp;2</span></a> to see how we approached aggregating scores</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>data_wemwbs <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> wemwbs_1<span class="sc">:</span>wemwbs_14, <span class="at">names_to =</span> <span class="st">"Questions"</span>, <span class="at">values_to =</span> <span class="st">"Scores"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">group_by</span>(pid) <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">summarise</span>(<span class="at">wemwbs_sum =</span> <span class="fu">sum</span>(Scores))</span>
<span id="cb3-5"><a href="#cb3-5"></a></span>
<span id="cb3-6"><a href="#cb3-6"></a>data_ballou <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">factor</span>(gender,</span>
<span id="cb3-8"><a href="#cb3-8"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Woman"</span>, <span class="st">"Man"</span>, <span class="st">"Non-binary"</span>)),</span>
<span id="cb3-9"><a href="#cb3-9"></a>         <span class="at">eduLevel =</span> <span class="fu">factor</span>(eduLevel,</span>
<span id="cb3-10"><a href="#cb3-10"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Completed Secondary School"</span>, <span class="st">"Some University but no degree"</span>, <span class="st">"University Bachelors Degree"</span>, <span class="st">"Vocational or Similar"</span>, <span class="st">"Graduate or professional degree (MA, MS, MBA, PhD, etc)"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb3-11"><a href="#cb3-11"></a>  <span class="fu">left_join</span>(data_wemwbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(pid)`</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="sec-chi_square" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="sec-chi_square">
<span class="header-section-number">6.5</span> Activity 4: Cross-tabulation Chi-square test</h2>
<p>A Cross-Tabulation Chi-Square Test, also known as a Chi-square test of association/independence, tests how one variable is associated with the distribution of outcomes in another variable.</p>
<p>We will be performing a Chi-Square test using the categorical variables <strong>gender</strong> and <strong>eduLevel</strong>:</p>
<ul>
<li>Potential research question: “Is there an association between gender and level of education in the population?”</li>
<li>Null Hypothesis (H<sub>0</sub>): “Gender and student status are independent; there is no association between gender and level of education.”</li>
<li>Alternative Hypothesis (H<sub>1</sub>): “Gender and student status are not independent; there is an association between gender and level of education.”</li>
</ul>
<section id="task-1-preparing-the-dataframe" class="level3" data-number="6.5.1"><h3 data-number="6.5.1" class="anchored" data-anchor-id="task-1-preparing-the-dataframe">
<span class="header-section-number">6.5.1</span> Task 1: Preparing the dataframe</h3>
<p>We need to select your variables of interest. We don’t have missing values in this dataset, but if your future dataframe might contain some, use <code>drop_na()</code> before you turn categorical variables into factors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>chi_square <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">select</span>(pid, gender, eduLevel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="task-2-compute-descriptives" class="level3" data-number="6.5.2"><h3 data-number="6.5.2" class="anchored" data-anchor-id="task-2-compute-descriptives">
<span class="header-section-number">6.5.2</span> Task 2: Compute descriptives</h3>
<p>We need to calculate counts for each combination of the variables. This is best done in a frequency table. This also allows us to check that we don’t have missing values in the cells. The function we are using does not work with missing values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>chi_square_frequency <span class="ot">&lt;-</span> chi_square <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="fu">count</span>(gender, eduLevel) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> eduLevel, <span class="at">values_from =</span> n)</span>
<span id="cb6-4"><a href="#cb6-4"></a></span>
<span id="cb6-5"><a href="#cb6-5"></a></span>
<span id="cb6-6"><a href="#cb6-6"></a>chi_square_frequency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 32%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">gender</th>
<th style="text-align: right;">Completed Secondary School</th>
<th style="text-align: right;">Some University but no degree</th>
<th style="text-align: right;">University Bachelors Degree</th>
<th style="text-align: right;">Vocational or Similar</th>
<th style="text-align: right;">Graduate or professional degree (MA, MS, MBA, PhD, etc)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Woman</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Man</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-binary</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We should be ok here, even though the count for non-binary/vocational is quite low.</p>
</section><section id="task-3-check-assumptions" class="level3" data-number="6.5.3"><h3 data-number="6.5.3" class="anchored" data-anchor-id="task-3-check-assumptions">
<span class="header-section-number">6.5.3</span> Task 3: Check assumptions</h3>
<section id="assumption-1-categorical-data" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-1-categorical-data">Assumption 1: categorical data</h4>
<p>The two variables should be categorical data measured either at an ordinal or nominal level.</p>
<p>We can confirm that for our dataset. Gender is <select class="webex-select"><option value="blank"></option>
<option value="x">ordinal</option>
<option value="answer">nominal</option></select>, and level of education is <select class="webex-select"><option value="blank"></option>
<option value="answer">ordinal</option>
<option value="x">nominal</option></select>.</p>
</section><section id="assumption-2-independent-observartions" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-2-independent-observartions">Assumption 2: Independent observartions</h4>
<p>The value of one observation in the dataset does not affect the value of any other observation.</p>
<p>And we assume as much for our data.</p>
</section><section id="assumption-3-cells-in-the-contingency-table-are-mutually-exclusive" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-3-cells-in-the-contingency-table-are-mutually-exclusive">Assumption 3: Cells in the contingency table are mutually exclusive</h4>
<p>Individuals can only belong to one cell in the contingency table.</p>
<p>We can confirm that by looking at the data and the contingency table.</p>
</section><section id="assumption-4-expected-frequencies-are-sufficiently-large" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-4-expected-frequencies-are-sufficiently-large">Assumption 4: Expected frequencies are sufficiently large</h4>
<p>Not an assumption that is listed consistently across various sources. When it is, it suggests that expected frequencies are larger than 5 or at least 80% of the the expected frequencies are above 5 and none of them are below 1. However, Danielle Navarro points out that this seems to be a “somewhat conservative” criterion and should be taken as “rough guidelines” only (see <a href="https://learningstatisticswithr.com/book/chisquare.html#chisqassumptions" target="_blank">https://learningstatisticswithr.com/book/chisquare.html#chisqassumptions</a>.</p>
<p>This is information, we can either compute manually (see lecture slides) or wait till we get the output from the inferential statistics later.</p>
</section></section><section id="task-4-create-an-appropriate-plot" class="level3" data-number="6.5.4"><h3 data-number="6.5.4" class="anchored" data-anchor-id="task-4-create-an-appropriate-plot">
<span class="header-section-number">6.5.4</span> Task 4: Create an appropriate plot</h3>
<p>Now we can create the appropriate plot. Which plot would you choose when building one from object <code>chi_square</code>? A <select class="webex-select"><option value="blank"></option>
<option value="answer">Barchart</option>
<option value="x">Histogram</option>
<option value="x">Scatterplot</option>
<option value="x">Violin-Boxplot</option></select> with geom layer <select class="webex-select"><option value="blank"></option>
<option value="x">geom_col</option>
<option value="answer">geom_bar</option>
<option value="x">geom_histogram</option>
<option value="x">geom_point</option>
<option value="x">geom_boxplot and geom_violin</option></select></p>
<p>Try first before looking at the solution. Feel free to practice adding other layers to make the plot pretty.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
One possible solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>… is a grouped bar chart.</p>
<p>I played about with the labels of the x-axis categories since the graduate label is super long. Google was my friend in this instance and showed me a nifty function called <code>label_wrap()</code> from the <code>scales</code> package which automatically adds line breaks after X characters. Here we chose 12; looked best. (See other options for long labels at <a href="https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/" target="_blank">https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/</a>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">ggplot</span>(chi_square, <span class="fu">aes</span>(<span class="at">x =</span> eduLevel, <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name =</span> <span class="st">"Gender"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Level of Education"</span>,</span>
<span id="cb7-5"><a href="#cb7-5"></a>                   <span class="at">labels =</span> <span class="fu">label_wrap</span>(<span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="task-5-compute-a-chi-square-test" class="level3" data-number="6.5.5"><h3 data-number="6.5.5" class="anchored" data-anchor-id="task-5-compute-a-chi-square-test">
<span class="header-section-number">6.5.5</span> Task 5: Compute a chi-square test</h3>
<p>Before we can do that, we need to turn our tibble into a dataframe - the <code>associationTest()</code> function we are using to compute the Chi-square test does not like tibbles. [<em>you have nooooo clue how long that took to figure out - let’s say the error message was not entirely useful</em>]</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>chi_square_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(chi_square)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can run the <code>associationTest()</code> function from the <code>lsr</code> package. The first argument is a formula. It starts with a <code>~</code> and then expects the 2 variables we want to associate connected with a <code>+</code>. The second argument is the dataframe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">associationTest</span>(<span class="at">formula =</span> <span class="sc">~</span> eduLevel <span class="sc">+</span> gender, <span class="at">data =</span> chi_square_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in associationTest(formula = ~eduLevel + gender, data = chi_square_df):
Expected frequencies too small: chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test of categorical association

Variables:   eduLevel, gender 

Hypotheses: 
   null:        variables are independent of one another
   alternative: some contingency exists between variables

Observed contingency table:
                                                         gender
eduLevel                                                  Woman Man Non-binary
  Completed Secondary School                                 63  70          9
  Some University but no degree                             118 125         23
  University Bachelors Degree                               169 250         20
  Vocational or Similar                                      42  34          4
  Graduate or professional degree (MA, MS, MBA, PhD, etc)    65  81         10

Expected contingency table under the null hypothesis:
                                                         gender
eduLevel                                                  Woman   Man
  Completed Secondary School                               59.9  73.4
  Some University but no degree                           112.2 137.5
  University Bachelors Degree                             185.2 227.0
  Vocational or Similar                                    33.8  41.4
  Graduate or professional degree (MA, MS, MBA, PhD, etc)  65.8  80.7
                                                         gender
eduLevel                                                  Non-binary
  Completed Secondary School                                    8.65
  Some University but no degree                                16.21
  University Bachelors Degree                                  26.75
  Vocational or Similar                                         4.88
  Graduate or professional degree (MA, MS, MBA, PhD, etc)       9.51

Test results: 
   X-squared statistic:  13.594 
   degrees of freedom:  8 
   p-value:  0.093 

Other information: 
   estimated effect size (Cramer's v):  0.079 
   warning: expected frequencies too small, results may be inaccurate</code></pre>
</div>
</div>
<p>The output is quite informative. It gives information about:</p>
<ul>
<li>the variables that were tested,</li>
<li>the null and alternative hypotheses,</li>
<li>a table with the observed frequencies (which matches what we calculated in <code>chi_square_assumptions</code> without the rows/columns of the missing values we removed),</li>
<li>an output of the frequencies you’d expect if the null hypothesis were true,</li>
<li>the result of the hypothesis test, and</li>
<li>the effect size Cramer’s v.</li>
</ul>
<p>And it gives us a <strong>warning message</strong> saying that expected frequencies are too small and that the chi-squared approximation may be incorrect. This ties in with Assumption 4. Depending on your stance on Assumption 4, you may or may not want to ignore the warning.</p>
<p>The p-value tells us that the null hypothesis is not being rejected, since the p-value is larger than 0.05.</p>
</section><section id="task-6-the-write-up" class="level3" data-number="6.5.6"><h3 data-number="6.5.6" class="anchored" data-anchor-id="task-6-the-write-up">
<span class="header-section-number">6.5.6</span> Task 6: The write-up</h3>
<p>The Chi-Square test revealed that there is no statistically significant association between Gender and Student Status, <span class="math inline">\(\chi^2(8) = 13.59, p = .093, V = .079\)</span>. The strength of the association between the variables is considered small. We therefore fail to reject the null hypothesis.</p>
</section></section><section id="sec-onesample" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="sec-onesample">
<span class="header-section-number">6.6</span> Activity 5: One-sample t-test</h2>
<p>The one-sample t-test is used to determine whether a sample comes from a population with a specific mean. This population mean is not always known, but is sometimes hypothesized.</p>
<p>We will be performing a one-sample t-test using the continuous variable <strong>wemwbs_sum</strong>. The <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official website for the Warwick-Edinburgh Mental Wellbeing Scales</a> states that the “WEMWBS has a mean score of 51.0 in general population samples in the UK with a standard deviation of 7 (Tennant et al., 2007)”.</p>
<ul>
<li>Potential research question: “Is the average mental well-being of gamers different from the general population’s average well-being?”</li>
<li>Null Hypothesis (H<sub>0</sub>): “The summed-up WEMWBS score of gamers is not different to 51.0.”</li>
<li>Alternative Hypothesis (H<sub>1</sub>): “The summed-up WEMWBS score of gamers is different from 51.0.”</li>
</ul>
<section id="task-1-preparing-the-dataframe-1" class="level3" data-number="6.6.1"><h3 data-number="6.6.1" class="anchored" data-anchor-id="task-1-preparing-the-dataframe-1">
<span class="header-section-number">6.6.1</span> Task 1: Preparing the dataframe</h3>
<p>We need to select your variables of interest.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>one_sample <span class="ot">&lt;-</span> data_ballou <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">select</span>(pid, wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="task-2-compute-descriptives-1" class="level3" data-number="6.6.2"><h3 data-number="6.6.2" class="anchored" data-anchor-id="task-2-compute-descriptives-1">
<span class="header-section-number">6.6.2</span> Task 2: Compute descriptives</h3>
<p>We want to compute means and standard deviations for our variable of interest. This should be straight forward. Try it yourself and then compare your result with the solution below.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>descriptives <span class="ot">&lt;-</span> one_sample <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">summarise</span>(<span class="at">mean_wemwbs =</span> <span class="fu">mean</span>(wemwbs_sum),</span>
<span id="cb13-3"><a href="#cb13-3"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(wemwbs_sum))</span>
<span id="cb13-4"><a href="#cb13-4"></a></span>
<span id="cb13-5"><a href="#cb13-5"></a>descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">mean_wemwbs</th>
<th style="text-align: right;">sd</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">45.42013</td>
<td style="text-align: right;">10.88615</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="task-3-create-an-appropriate-plot" class="level3" data-number="6.6.3"><h3 data-number="6.6.3" class="anchored" data-anchor-id="task-3-create-an-appropriate-plot">
<span class="header-section-number">6.6.3</span> Task 3: Create an appropriate plot</h3>
<p>This is the one you want to include in your report, so make sure everything is clearly labelled. Which plot would you choose? Start creating one first before comparing with the solution below.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>  <span class="fu">geom_violin</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> <span class="co"># alpha for opacity, fill for adding colour</span></span>
<span id="cb14-3"><a href="#cb14-3"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co"># change width of the boxes</span></span>
<span id="cb14-4"><a href="#cb14-4"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb14-6"><a href="#cb14-6"></a>       <span class="at">y =</span> <span class="st">"Total WEMWBS Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="task-4-check-assumptions" class="level3" data-number="6.6.4"><h3 data-number="6.6.4" class="anchored" data-anchor-id="task-4-check-assumptions">
<span class="header-section-number">6.6.4</span> Task 4: Check assumptions</h3>
<section id="assumption-1-continuous-dv" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-1-continuous-dv">Assumption 1: Continuous DV</h4>
<p>The dependent variable needs to be measured at interval or ratio level. We can confirm that by looking at <code>one_sample</code>.</p>
</section><section id="assumption-2-data-are-independent" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-2-data-are-independent">Assumption 2: Data are independent</h4>
<p>There is no relationship between the observations. Whilst this is an important assumption, it’s not one we can really test for. It has more to do with study design. Anyway, we assume this assumption holds for our data.</p>
</section><section id="assumption-3-no-significant-outliers" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-3-no-significant-outliers">Assumption 3: No significant outliers</h4>
<p>We can check for that visually, for example in the violin-boxplot above.</p>
<p>It appears that there is one outlier on the lower tail, however, when inspecting the data in <code>one_sample</code>, we can see that it’s one person who got a score of 14 which is a possible value. Furthermore, when sample sizes are sufficiently large, like ours with 1083 participants, removing a single outlier makes not much sense. So we have checked this assumption, consider this outlier not significant, and therefore keep this observation in the dataset.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are taking any of the outliers out, you need to recalculated the descriptive stats.</p>
</div>
</div>
</section><section id="assumption-4-dv-should-be-approximately-normally-distributed" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-4-dv-should-be-approximately-normally-distributed">Assumption 4: DV should be approximately normally distributed</h4>
<p>We can already check normality from the violin-boxplot above but you could plot a histogram, a density plot, or a qqplot as an alternative to assess normality visually.</p>
<p>All of these options show that <strong>the data is normally distributed</strong>. That means, we will conduct a parametric test, i.e.&nbsp;a one-sample t-test.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternatives to visually assess normality
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Histogram</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Density plot</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Q-Q plot</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>We’ve already covered histograms in <a href="05-dataviz2.html"><span>Chapter&nbsp;5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"magenta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>A density plot shows a smooth distribution curve of the data. The curve represents the proportion of the data in each range rather than the frequency. This means that the height of the curve doesn’t show how many times a value appears but rather the proportion of the data that falls into that range.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">x =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"magenta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Q-Q plot stands for Quantile-Quantile Plot and compare two distributions by matching a common set of quantiles. It basically means that it’s comparing the distribution you have in your data with a normal distribution and plots this along a 45 degree line.</p>
<p><strong>If the dots in the Q-Q plot fall roughly along that line, you can assume normality of the data. If they stray away from the line (and worse in some sort of pattern), we might not assume normality and conduct a non-parametric test instead. For the non-parametric equivalent, see <a href="#sec-alternative_one_sample"><span>Section&nbsp;6.7</span></a>.</strong></p>
<p>We can either use the package <code>car</code> or <code>qqplotr</code> to build the qqplot.</p>
<ul>
<li>The function <code>qqPlot()</code> is a single line but uses BaseR coding (i.e., the <code>$</code> symbol) to access the column in the data object.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Version 1 with the car package</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="fu">qqPlot</span>(one_sample<span class="sc">$</span>wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 295 394</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-qqplot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/fig-qqplot1-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.1: Q-Q plot created with the car package</figcaption></figure>
</div>
</div>
</div>
<ul>
<li>If you have gotten used to ggplot by now, and prefer avoiding BaseR, you can use the package <code>qqplotr</code>. The downside is that you have to add the points, the line, and the confidence envelope yourself. On the plus, it has layers like ggplot, and is more customisable (just in case you wanted to look at something more colourful in the 2 seconds it’ll take you to assess normality).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Version 2 with package qqplotr</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="fu">ggplot</span>(one_sample, <span class="fu">aes</span>(<span class="at">sample =</span> wemwbs_sum)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">stat_qq_band</span>(<span class="at">fill =</span> <span class="st">"#FB8D61"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4"></a>  <span class="fu">stat_qq_line</span>(<span class="at">colour =</span> <span class="st">"#FB8D61"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5"></a>  <span class="fu">stat_qq_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-qqplot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="06-chi-square-one-sample_files/figure-html/fig-qqplot2-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.2: Q-Q plot created with the qqplotr package</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>You can also assess normality with the <strong>Shapiro-Wilk’s test</strong>. The null hypothesis is that the population is distributed normally. Therefore, if the p-value of the Shapiro-Wilk’s test smaller than .05, normality is rejected.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Shapiro-Wilk is a good method for small sample sizes (e.g., smaller than 50 samples). If you have large sample sizes, Shapiro-Wilk will definitely produce a significant p-value regardless of what the distribution looks like. So don’t rely on its output when you have large sample sizes.</p>
</div>
</div>
<p>The function in R is <code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code> and it’s built into BaseR, meaning, we need our data object, the <code>$</code> and the column we want to address.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">shapiro.test</span>(one_sample<span class="sc">$</span>wemwbs_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  one_sample$wemwbs_sum
W = 0.99404, p-value = 0.0002619</code></pre>
</div>
</div>
<p>No surprise here, the test shows p &lt; .001 because we have more than 1000 participants. Nevertheless, if you had a smaller sample and you needed to write this result up in your report, you would report it in APA style: <span class="math inline">\(W = .99, p &lt; .001\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report-writing Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Either choose visual or computational inspection for normality tests. NO NEED TO DO BOTH!!!</p>
<ul>
<li>State what method you used and your reasons for choosing the method (visual/computational and what plot/test you used)</li>
<li>State the outcome of the test - for visual inspection just say whether normality assumption held or not (no need to include that extra plot in the results section). For computational methods, report the test result in APA style</li>
<li>State the conclusions you draw from it - parametric or non-parametric test</li>
</ul>
</div>
</div>
</section></section><section id="task-5-compute-a-one-sample-t-test-and-effect-size" class="level3" data-number="6.6.5"><h3 data-number="6.6.5" class="anchored" data-anchor-id="task-5-compute-a-one-sample-t-test-and-effect-size">
<span class="header-section-number">6.6.5</span> Task 5: Compute a One-sample t-test and effect size</h3>
<p>We can use the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function to compute a one-sample t-test. The <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function is part of BaseR, and yes, you guessed it, our first argument has to follow the pattern <code>data$column</code>. The second argument (<code>mu</code>) lists the population mean we are testing our sample against (here 51.0). The <code>alternative</code> is “two.sided” by default, so you could leave the argument out.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">t.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">51.0</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  one_sample$wemwbs_sum
t = -16.868, df = 1082, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 51
95 percent confidence interval:
 44.77106 46.06920
sample estimates:
mean of x 
 45.42013 </code></pre>
</div>
</div>
<p>The output is quite informative. It gives us information about:</p>
<ul>
<li>the variable column that was tested,</li>
<li>the t value, degrees of freedom, and p,</li>
<li>the alternative hypothesis,</li>
<li>a 95% confidence interval,</li>
<li>and the mean of the column (which matches the one we computed in the descriptive - yay)</li>
</ul>
<p>What it doesn’t give us is an <strong>effect size</strong>. Meh. So we have to compute one ourselves.</p>
<p>We will calculate <strong>Cohen’s d</strong> using the function <code>cohensD()</code> from the <code>lsr</code> package. Similar to the t-test we just conducted, the first argument is <code>data$column</code>, the second argument is <code>mu</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">cohensD</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">51.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5125662</code></pre>
</div>
</div>
</section><section id="task-6-sensitivity-power-analysis" class="level3" data-number="6.6.6"><h3 data-number="6.6.6" class="anchored" data-anchor-id="task-6-sensitivity-power-analysis">
<span class="header-section-number">6.6.6</span> Task 6: Sensitivity power analysis</h3>
<p>A <strong>sensitivity power analysis allows you to determine the minimum effect size that the study could reliably detect</strong> given the number of participants you have in the sample, the alpha level at 0.05, and an assumed power of 0.8.</p>
<p>The function we need to compute this is <code>pwr.t.test()</code> which is part of the <code>pwr</code> package. There are 4 factors - the APES (alpha, power, effect size, and sample size) - if you have 3, you can calculate the 4th. As stated above, we have 3. We also need to specify the <code>type</code>, i.e., that we are using it for a one-sample t-test, and that <code>alternative</code> is “two.sided” because we have a non-directional hypothesis.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">pwr.t.test</span>(<span class="at">n =</span> <span class="dv">1083</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.8</span>, <span class="at">type =</span> <span class="st">"one.sample"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 1083
              d = 0.08520677
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
</div>
<p>So the smallest effect size we can detect with a sample size of 1083, an alpha level of 0.05, and power of 0.8 is 0.09. This is a smaller value than the actual effect size we calculated with our CohensD function above (i.e., 0.51) which means our analysis is sufficiently powered.</p>
</section><section id="task-7-the-write-up" class="level3" data-number="6.6.7"><h3 data-number="6.6.7" class="anchored" data-anchor-id="task-7-the-write-up">
<span class="header-section-number">6.6.7</span> Task 7: The write-up</h3>
<p>A one-sample t-test was computed to determine whether the average mental well-being of gamers as measured by the WEMWBS was different to the population well-being mean. The average WEMWBS of the gamers <span class="math inline">\((N = 1083, M = 45.42, SD = 10.89)\)</span> was significantly lower than the population mean well-being score of 51.0, <span class="math inline">\(t(1082) = 16.87, p &lt; .001, d = .51\)</span>. The strength of the effect is considered medium and the study was sufficiently powered. We therefore reject the null hypothesis in favour of H<sub>1</sub>.</p>
</section></section><section id="sec-alternative_one_sample" class="level2" data-number="6.7"><h2 data-number="6.7" class="anchored" data-anchor-id="sec-alternative_one_sample">
<span class="header-section-number">6.7</span> Activity 6: Non-parametric alternative</h2>
<p>If any of the assumptions are violated, you need to switch to the non-parametric alternative. For the one-sample t-test, this is a <strong>One-sample Wilcoxon signed-rank test</strong>. Instead of the mean, it compares the median of a sample against a single value (i.e., the population median).</p>
<p>That means we need to find the population median, and calculate some summary stats for our sample:</p>
<ul>
<li>The population median is listed in a supporting document on the <a href="https://warwick.ac.uk/fac/sci/med/research/platform/wemwbs/using/howto/" target="_blank">official WEMWBS website</a> as 53.0.</li>
<li>We can easily calculate the summary statistics using the function summary.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">summary</span>(one_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pid              wemwbs_sum   
 Length:1083        Min.   :14.00  
 Class :character   1st Qu.:38.00  
 Mode  :character   Median :46.00  
                    Mean   :45.42  
                    3rd Qu.:53.00  
                    Max.   :70.00  </code></pre>
</div>
</div>
<p>The function to compute a one-sample Wilcoxon test test is <code><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test()</a></code>. It’s part of BaseR and code-wise, it works very similar to the one-sample t-test.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">wilcox.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  one_sample$wemwbs_sum
V = 87218, p-value &lt; 2.2e-16
alternative hypothesis: true location is not equal to 53</code></pre>
</div>
</div>
<p>As we can see, the output gives us a V value, but we need to report a Z value in the final write-up. Unfortunately, we have to calculate Z manually. According to Andy Field (2012, p.&nbsp;665), we need to use the qnorm function on the halved p-value from our Wilcoxon test above.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="co"># storing the p-value</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>p_wilcoxon <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>)<span class="sc">$</span>p.value</span>
<span id="cb32-3"><a href="#cb32-3"></a></span>
<span id="cb32-4"><a href="#cb32-4"></a><span class="co"># calculate the z value from half the p-value</span></span>
<span id="cb32-5"><a href="#cb32-5"></a>z <span class="ot">=</span> <span class="fu">qnorm</span>(p_wilcoxon<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb32-6"><a href="#cb32-6"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19.12264</code></pre>
</div>
</div>
<p>We also need to calculate the effect size <code>r</code>, which we can do via the <code>wilcoxonOneSampleR</code> from the <code>rcompanion</code> package. The default value will be 3 decimal places, but you can change that with the <code>digits</code> argument.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">wilcoxonOneSampleR</span>(one_sample<span class="sc">$</span>wemwbs_sum, <span class="at">mu =</span> <span class="fl">53.0</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    r 
-0.59 </code></pre>
</div>
</div>
<p>Now we have all the numbers we need to write up the results:</p>
<p>A One-sample Wilcoxon signed-rank test was used to compare Gamers’ mental-wellbeing scores (Mdn = 46.0) to the population median of 53.0. The test showed a significant difference, <span class="math inline">\(Z = -19.12, p &lt; .001, r = .590\)</span>. The strength of the effect is considered medium. We therefore reject the null hypothesis in favour of H<sub>1</sub>.</p>
</section><section id="pair-coding" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="pair-coding"><span style="color: #F39C12; text-transform: uppercase;">Pair-coding</span></h2>
</section><section id="test-your-knowledge-on-chapters-3-and-4" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="test-your-knowledge-on-chapters-3-and-4"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge on Chapters 3 and 4</span></h2>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-dataviz2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-independent.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">CC-BY (2024) Gaby Mahrholz</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>