<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Data skills book for Level 2 Psychology students at the School of Psychology and Neuroscience at the University of Glasgow">
<title>Analysis - 11&nbsp; Multiple regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12-one-way-anova.html" rel="next">
<link href="./10-regression.html" rel="prev">
<link href="./images/logos/logo_analysis.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
<link rel="stylesheet" href="include/custom.scss">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-multiple-regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analysis</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Projects and R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data wrangling I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data wrangling II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data viz I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-dataviz2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data viz II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-chi-square-one-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chi-square and one-sample t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-independent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-paired.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Paired t-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-multiple-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-one-way-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-updating-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Updating R, RStudio, and packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-d-symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Symbols</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-x-How-to-cite-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Citing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-y-license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#intended-learning-outcomes" id="toc-intended-learning-outcomes" class="nav-link active" data-scroll-target="#intended-learning-outcomes">Intended Learning Outcomes</a></li>
  <li><a href="#individual-walkthrough" id="toc-individual-walkthrough" class="nav-link" data-scroll-target="#individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></a></li>
  <li><a href="#activity-1-setup-download-the-data" id="toc-activity-1-setup-download-the-data" class="nav-link" data-scroll-target="#activity-1-setup-download-the-data"><span class="header-section-number">11.1</span> Activity 1: Setup &amp; download the data</a></li>
  <li><a href="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" id="toc-activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="nav-link" data-scroll-target="#activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data"><span class="header-section-number">11.2</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</a></li>
  <li>
<a href="#activity-3-compute-descriptives" id="toc-activity-3-compute-descriptives" class="nav-link" data-scroll-target="#activity-3-compute-descriptives"><span class="header-section-number">11.3</span> Activity 3: Compute descriptives</a>
  <ul class="collapse">
<li><a href="#well-being" id="toc-well-being" class="nav-link" data-scroll-target="#well-being"><span class="header-section-number">11.3.1</span> Well-being</a></li>
  <li><a href="#screentime" id="toc-screentime" class="nav-link" data-scroll-target="#screentime"><span class="header-section-number">11.3.2</span> Screentime</a></li>
  </ul>
</li>
  <li><a href="#activity-4-recreating-the-plot-from-the-paper" id="toc-activity-4-recreating-the-plot-from-the-paper" class="nav-link" data-scroll-target="#activity-4-recreating-the-plot-from-the-paper"><span class="header-section-number">11.4</span> Activity 4: Recreating the plot from the paper</a></li>
  <li>
<a href="#activity-5-dataframe-for-the-regression-model" id="toc-activity-5-dataframe-for-the-regression-model" class="nav-link" data-scroll-target="#activity-5-dataframe-for-the-regression-model"><span class="header-section-number">11.5</span> Activity 5: Dataframe for the regression model</a>
  <ul class="collapse">
<li><a href="#final-data-wrangling-steps" id="toc-final-data-wrangling-steps" class="nav-link" data-scroll-target="#final-data-wrangling-steps"><span class="header-section-number">11.5.1</span> Final data wrangling steps</a></li>
  <li><a href="#mean-centering-variables" id="toc-mean-centering-variables" class="nav-link" data-scroll-target="#mean-centering-variables"><span class="header-section-number">11.5.2</span> Mean-centering variables</a></li>
  </ul>
</li>
  <li><a href="#activity-6-compute-the-regression-confidence-intervals-and-effect-size" id="toc-activity-6-compute-the-regression-confidence-intervals-and-effect-size" class="nav-link" data-scroll-target="#activity-6-compute-the-regression-confidence-intervals-and-effect-size"><span class="header-section-number">11.6</span> Activity 6: Compute the regression, confidence intervals, and effect size</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">11.7</span> Your Turn</a></li>
  <li><a href="#activity-7-visualising-interactions" id="toc-activity-7-visualising-interactions" class="nav-link" data-scroll-target="#activity-7-visualising-interactions"><span class="header-section-number">11.8</span> Activity 7: Visualising interactions</a></li>
  <li><a href="#activity-8-check-assumptions" id="toc-activity-8-check-assumptions" class="nav-link" data-scroll-target="#activity-8-check-assumptions"><span class="header-section-number">11.9</span> Activity 8: Check assumptions</a></li>
  <li><a href="#activity-9-sensitivity-power-analysis" id="toc-activity-9-sensitivity-power-analysis" class="nav-link" data-scroll-target="#activity-9-sensitivity-power-analysis"><span class="header-section-number">11.10</span> Activity 9: Sensitivity power analysis</a></li>
  <li><a href="#activity-10-the-write-up" id="toc-activity-10-the-write-up" class="nav-link" data-scroll-target="#activity-10-the-write-up"><span class="header-section-number">11.11</span> Activity 10: The write-up</a></li>
  <li><a href="#pair-coding" id="toc-pair-coding" class="nav-link" data-scroll-target="#pair-coding"><span style="color: #F39C12; text-transform: uppercase;">Pair-coding</span></a></li>
  <li><a href="#test-your-knowledge" id="toc-test-your-knowledge" class="nav-link" data-scroll-target="#test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-reg_mult" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="intended-learning-outcomes" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="intended-learning-outcomes">Intended Learning Outcomes</h2>
<p>By the end of this chapter you should be able to:</p>
<ul>
<li>Apply and interpret multiple linear regression models.</li>
<li>Interpret coefficients from individual predictors and interactions.</li>
<li>Visualise interactions as model predictions to understand and communicate your findings.</li>
<li>Calculate statistical power for a multiple regression model.</li>
</ul>
<p>In the previous chapter, we have looked at simple regressions - predicting an outcome variable using one predictor variable. In this chapter, we will expand on that and look at scenarios where we predict an outcome using more than one predictor in the model - hence, multiple regression.</p>
</section><section id="individual-walkthrough" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="individual-walkthrough"><span style="color: #F39C12; text-transform: uppercase;">Individual Walkthrough</span></h2>
</section><section id="activity-1-setup-download-the-data" class="level2" data-number="11.1"><h2 data-number="11.1" class="anchored" data-anchor-id="activity-1-setup-download-the-data">
<span class="header-section-number">11.1</span> Activity 1: Setup &amp; download the data</h2>
<p>This week, we will be working with a new dataset. Follow the steps below to set up your project:</p>
<ul>
<li>
<strong>Create a new project</strong> and name it something meaningful (e.g., “2B_chapter11”, or “11_multople_regression”). See <a href="01-basics.html#sec-project"><span>Section&nbsp;1.2</span></a> if you need some guidance.</li>
<li>
<strong>Create a new <code>.Rmd</code> file</strong> and save it to your project folder. See <a href="01-basics.html#sec-rmd"><span>Section&nbsp;1.3</span></a> if you need help.</li>
<li>Delete everything after the setup code chunk (e.g., line 12 and below)</li>
<li>
<strong>Download the new dataset</strong> here: <a href="data/data_ch11.zip" title="download">data_ch11.zip</a>. The zip folder includes:
<ul>
<li>the demographics data file (<code>Przybylski_2017_demographics.csv</code>)</li>
<li>the screentime data file (<code>Przybylski_2017_screentime.csv</code>)</li>
<li>the wellbeing data file (<code>Przybylski_2017_wellbeing.csv</code>), and the</li>
<li>the codebook (<code>Przybylski_2017_Codebook.xlsx</code>).</li>
</ul>
</li>
<li>Extract the data file from the zip folder and place it in your project folder. If you need help, see <a href="01-basics.html#sec-download_data_ch1"><span>Section&nbsp;1.4</span></a>.</li>
</ul>
<p><strong>Citation</strong></p>
<blockquote class="blockquote">
<p>Przybylski, A. K., &amp; Weinstein, N. (2017). A Large-Scale Test of the Goldilocks Hypothesis: Quantifying the Relations Between Digital-Screen Use and the Mental Well-Being of Adolescents. <em>Psychological Science, 28</em>(2), 204-215. <a href="https://doi.org/10.1177/0956797616678438" target="_blank">https://doi.org/10.1177/0956797616678438</a></p>
</blockquote>
<p><strong>Abstract</strong></p>
<blockquote class="blockquote">
<p>Although the time adolescents spend with digital technologies has sparked widespread concerns that their use might be negatively associated with mental well-being, these potential deleterious influences have not been rigorously studied. Using a preregistered plan for analyzing data collected from a representative sample of English adolescents (<em>n</em> = 120,115), we obtained evidence that the links between digital-screen time and mental well-being are described by quadratic functions. Further, our results showed that these links vary as a function of when digital technologies are used (i.e., weekday vs.&nbsp;weekend), suggesting that a full understanding of the impact of these recreational activities will require examining their functionality among other daily pursuits. Overall, the evidence indicated that moderate use of digital technology is not intrinsically harmful and may be advantageous in a connected world. The findings inform recommendations for limiting adolescents’ technology use and provide a template for conducting rigorous investigations into the relations between digital technology and children’s and adolescents’ health.</p>
</blockquote>
<p>The data is available on OSF: <a href="https://osf.io/bk7vw/" target="_blank">https://osf.io/bk7vw/</a></p>
<p><strong>Changes made to the dataset</strong></p>
<ul>
<li>We converted the SPSS file into a CSV file. There is a CSV file in their OSF folder, however, it does have any labels or values explained. Therefore, we started from the SPSS file that has a bit more information.</li>
<li>We reduced the dataset by selecting some of the variables relating to demographics, screentime and wellbeing.</li>
<li>Data was separated into 3 files: demographics, screentime, and wellbeing.</li>
<li>Screentime values were recoded and display hours according to the codebook.</li>
<li>Rows with missing values were excluded in <code>screentime.csv</code> and <code>wellbeing.csv</code>.</li>
<li>We also created a codebook for the variables we selected.</li>
</ul></section><section id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data" class="level2" data-number="11.2"><h2 data-number="11.2" class="anchored" data-anchor-id="activity-2-load-in-the-library-read-in-the-data-and-familiarise-yourself-with-the-data">
<span class="header-section-number">11.2</span> Activity 2: Load in the library, read in the data, and familiarise yourself with the data</h2>
<p>Today, we will be using the packages <code>tidyverse</code>, <code>sjPlot</code>, <code>performance</code>, and <code>pwr</code>, along with the datasets <code>Alter_2024_data.csv</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>???</span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a>demo <span class="ot">&lt;-</span> ???</span>
<span id="cb1-4"><a href="#cb1-4"></a>screentime <span class="ot">&lt;-</span> ???</span>
<span id="cb1-5"><a href="#cb1-5"></a>wellbeing <span class="ot">&lt;-</span> ???</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(performance)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(pwr)</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a>demo <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Przybylski_2017_demographics.csv"</span>)</span>
<span id="cb2-7"><a href="#cb2-7"></a>screentime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Przybylski_2017_screentime.csv"</span>)</span>
<span id="cb2-8"><a href="#cb2-8"></a>wellbeing <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Przybylski_2017_wellbeing.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>As always, take a moment to familiarise yourself with the data before starting your analysis.</p>
<p>Once you have explored the data objects and the codebook, try and answer the following questions:</p>
<ul>
<li>The variable Gender is located in the object named <select class="webex-select"><option value="blank"></option>
<option value="answer">demo</option>
<option value="x">wellbeing</option>
<option value="x">screentime</option></select>.</li>
<li>The wellbeing data is in <select class="webex-select"><option value="blank"></option>
<option value="x">long</option>
<option value="answer">wide</option></select> format and contains observations from <input class="webex-solveme nospaces" size="10" data-answer="[&quot;102580&quot;,&quot;102,580&quot;]"> participants.</li>
<li>The wellbeing questionnaire has <input class="webex-solveme nospaces" size="2" data-answer="[&quot;14&quot;]"> items.</li>
<li>Individual participants in this data set are identified by the variable called <input class="webex-solveme nospaces ignorecase" size="9" data-answer="[&quot;Serial&quot;]">. This variable will allow us to link information across the three tables.</li>
<li>Are there any missing data points? <select class="webex-select"><option value="blank"></option>
<option value="x">Yes</option>
<option value="answer">No</option></select>
</li>
</ul>
<section id="potential-research-question-hypthesis" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="potential-research-question-hypthesis">Potential Research Question &amp; Hypthesis</h4>
<p>There is ongoing debate about the impact of smartphones on well-being, particularly among children and teenagers. Hence, we will examine whether smartphone use predicts mental well-being and whether this relationship differs between male and female adolescents.</p>
<ul>
<li>
<strong>Potential research question</strong>: “Does smartphone use predict mental well-being, and does this relationship differ between male and female adolescents?”</li>
<li>
<strong>Null Hypothesis (H<sub>0</sub>)</strong>: “Smartphone use does not predict mental well-being, and there is no difference in this relationship between male and female adolescents.”</li>
<li>
<strong>Alternative Hypothesis (H<sub>1</sub>)</strong>: “Smartphone use is a significant predictor of mental well-being, and the effect of smartphone use on well-being differs between male and female adolescents.”</li>
</ul>
<p>Note that in this analysis, we have:</p>
<ul>
<li>a continuous* DV, well-being;</li>
<li>a continuous* predictor, screen time;</li>
<li>a categorical predictor, gender.</li>
</ul>
<p><em>* these variables are only quasi-continuous, inasmuch as only discrete values are possible. However, there are a sufficient number of discrete categories that we can treat them as effectively continuous.</em></p>
</section></section><section id="activity-3-compute-descriptives" class="level2" data-number="11.3"><h2 data-number="11.3" class="anchored" data-anchor-id="activity-3-compute-descriptives">
<span class="header-section-number">11.3</span> Activity 3: Compute descriptives</h2>
<p>Today, we will be dealing with the majority of data wrangling in the following activities. So let’s bring Computing descriptives forward</p>
<section id="well-being" class="level3" data-number="11.3.1"><h3 data-number="11.3.1" class="anchored" data-anchor-id="well-being">
<span class="header-section-number">11.3.1</span> Well-being</h3>
<p>We need to do some initial data wrangling on <code>wellbeing</code>. For each participant, compute the total score for the mental health questionnaire. Store the output in a new data object called <code>wemwbs</code>.</p>
<p>The new dataset should have two variables:</p>
<ul>
<li>
<code>Serial</code> - the participant ID.</li>
<li>
<code>WEMWBS_sum</code> - the total WEMWBS score.</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>wemwbs <span class="ot">&lt;-</span> wellbeing <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"WB"</span>), <span class="co"># -Serial or WBOptimf:WBCheer also work</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>               <span class="at">names_to =</span> <span class="st">"Qs"</span>, </span>
<span id="cb3-4"><a href="#cb3-4"></a>               <span class="at">values_to =</span> <span class="st">"Score"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>  <span class="fu">group_by</span>(Serial) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>  <span class="fu">summarise</span>(<span class="at">WEMWBS_sum =</span> <span class="fu">sum</span>(Score)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>In the original paper, Przybylski and Weinstein (2017) reported: “Scores ranged from 14 to 70 (M = 47.52, SD = 9.55)”. Can you reproduce these values?</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Means and standard deviations should not be an issue at this stage, but how would you calculate the minimum and the maximum?</p>
<p>We addressed it briefly in <a href="02-wrangling.html"><span>Chapter&nbsp;2</span></a> and it’s more intuitive than you think…</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Yes, you are correct. The functions <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code> and <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code> calculate minimum and maximum values respectively.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>wemwbs <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(WEMWBS_sum),</span>
<span id="cb4-3"><a href="#cb4-3"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(WEMWBS_sum),</span>
<span id="cb4-4"><a href="#cb4-4"></a>            <span class="at">min =</span> <span class="fu">min</span>(WEMWBS_sum),</span>
<span id="cb4-5"><a href="#cb4-5"></a>            <span class="at">max =</span> <span class="fu">max</span>(WEMWBS_sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">47.52189</td>
<td style="text-align: right;">9.546374</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">70</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="screentime" class="level3" data-number="11.3.2"><h3 data-number="11.3.2" class="anchored" data-anchor-id="screentime">
<span class="header-section-number">11.3.2</span> Screentime</h3>
<p>We want to calculate means and standard deviations of the hours of smartphone use during the week and on the weekend.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We are just computing the information rather than storing it. If you want to save the output as an object to your <code>Global Environment</code>, feel free to do so.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>screentime <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">summarise</span>(<span class="at">smart_weekday_mean =</span> <span class="fu">mean</span>(Smart_wk),</span>
<span id="cb5-3"><a href="#cb5-3"></a>            <span class="at">smart_weekday_sd =</span> <span class="fu">sd</span>(Smart_wk),</span>
<span id="cb5-4"><a href="#cb5-4"></a>            <span class="at">smart_weekend_mean =</span> <span class="fu">mean</span>(Smart_we),</span>
<span id="cb5-5"><a href="#cb5-5"></a>            <span class="at">smart_weekend_sd =</span> <span class="fu">sd</span>(Smart_we))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 26%">
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: right;">smart_weekday_mean</th>
<th style="text-align: right;">smart_weekday_sd</th>
<th style="text-align: right;">smart_weekend_mean</th>
<th style="text-align: right;">smart_weekend_sd</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">2.910655</td>
<td style="text-align: right;">2.33917</td>
<td style="text-align: right;">3.517003</td>
<td style="text-align: right;">2.497139</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section><section id="activity-4-recreating-the-plot-from-the-paper" class="level2" data-number="11.4"><h2 data-number="11.4" class="anchored" data-anchor-id="activity-4-recreating-the-plot-from-the-paper">
<span class="header-section-number">11.4</span> Activity 4: Recreating the plot from the paper</h2>
<p>If there was a bit of a challenge, this is it. We can wrangle the data to plot the data like the original article (shown below).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/figure_Przybylski.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig. 1. Mental well-being as a function of daily digital-screen time on weekdays and weekends. Results are shown separately for time spent (a) watching TV and movies, (b) playing video games, (c) using computers, and (d) using smartphones. Error bars denote the 95% confidence intervals for the observed means. (Przybylski &amp; Weinstein, 2017)</figcaption></figure>
</div>
<p>The graph shows that smartphone use of more than 1 hour per day is associated with increasingly negative well-being.</p>
<p>We can plot the relationship between well-being and hours of technology use, split into four categories of technology (video games, computers, smartphones, TV).</p>
<p>There is some faceting going on and you will not have been introduced to all the functions we need.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s start with some observations:</p>
<ol type="A">
<li><p>We need information on hours of screentime (x-axis) and mental well-being (y-axis), that is currently stored in <code>screentime</code> and in <code>wellbeing</code>, respectively. That means we have to join the two datasets at some point.</p></li>
<li><p>Our dataframe needs to be restructured into longformat so that we can use the function <code>facet_wrap()</code>.</p></li>
<li><p>We need to process weekend and weekday data separately. At the moment, it is hidden in the column labels, so we need to think about how we can access the information.</p></li>
<li><p>The plot shows us average hours and wellbeing scores per weekday/weekend. So we need to compute them.</p></li>
<li><p>We have to use a lineplot (e.g., <code>geom_line</code>) and a scatterplot because we need a line with dots.</p></li>
<li><p>And it would be nice if the different categories are clearly labelled in the plot rather than having to mention them below the figure</p></li>
</ol>
</div>
</div>
<p>Now it’s just figuring out which sequence we need them to be in. There are steps to do (or that easier to do) in the dataframe and then there is plotting.</p>
<p>Sooo, let’s start with any changes we can apply to the dataframe <code>screentime</code>. We should store the new output in an object called <code>screen_long</code>.</p>
<p><strong>Step 1</strong>: Pivot <code>screentime</code> into long format.</p>
<p><strong>Step 2</strong>: To be able to access information on weekday/weekend and on the four categories of technology, we need to separate information in the current column levels. Anything before the separator <code>_</code> is category of technology; anything after is related to weekday/weekend (e.g., <code>Watch_we</code>, <code>Smart_wk</code>). That is easier done when the data is in long format.</p>
<p><strong>Step 3</strong>: The values <code>Watch</code>, <code>Smart</code>, <code>we</code> or <code>wk</code> are not really informative and these will be the labels that are displayed on the facets and legends in the final plot. Tidying a legend label can still be done in the plots, but for facets it’s a nightmare, so better do that here. So here we want to relabel values as follows:</p>
<ul>
<li>“Watch” should become “Watching TV”,</li>
<li>“Comp” -&gt; “Playing Video Games”,</li>
<li>“Comph” -&gt; “Using Computers”,</li>
<li>“Smart” -&gt; “Using Smartphone”,</li>
<li>“wk” -&gt; “Weekdays”, and</li>
<li>“we” ~ “Weekends”.</li>
</ul>
<p><strong>Step 4</strong>: We have all information for the plot in one place. Join <code>screen_long</code> and <code>wemwbs</code> together so that participants have values in both dataframes.</p>
<p><strong>Step 5</strong>: For each technology type and screentime hours, compute averages of well-being for Weekdays and Weekends. Maybe steps 4 and 5 are better stored in a separate data object called <code>dat_means</code>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Step 1: uses <code>pivot_longer()</code>
</li>
<li>Step 2: remember the <code>separate()</code> function. It will come in handy here. And the separator needs to be “_“.</li>
<li>Step 3: requires a simple recoding of the values, no conditional statements necessary</li>
<li>Step 4: <code>inner_join()</code>
</li>
<li>Step 5: think about what column you need to <code>group_by()</code> before you can <code>summarise()</code>
</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We are just computing the information rather than storing it. If you want to save it as an object to your <code>Global Environment</code>, feel free to do so.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>screen_long <span class="ot">&lt;-</span> screentime <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="co"># Step 1: Pivot into long format</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Serial, <span class="at">names_to =</span> <span class="st">"headings"</span>, <span class="at">values_to =</span> <span class="st">"hours"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="co"># Step 2: `separate()`</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>  <span class="fu">separate</span>(<span class="at">col =</span> headings, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"technology_type"</span>, <span class="st">"day"</span>), <span class="at">sep =</span> <span class="st">"_"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="co"># Step 3: Recode the values</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>  <span class="fu">mutate</span>(<span class="at">technology_type =</span> <span class="fu">case_match</span>(technology_type,</span>
<span id="cb6-8"><a href="#cb6-8"></a>                                      <span class="st">"Watch"</span> <span class="sc">~</span> <span class="st">"Watching TV"</span>,</span>
<span id="cb6-9"><a href="#cb6-9"></a>                                      <span class="st">"Comp"</span> <span class="sc">~</span> <span class="st">"Playing Video Games"</span>,</span>
<span id="cb6-10"><a href="#cb6-10"></a>                                      <span class="st">"Comph"</span> <span class="sc">~</span> <span class="st">"Using Computers"</span>,</span>
<span id="cb6-11"><a href="#cb6-11"></a>                                      <span class="st">"Smart"</span> <span class="sc">~</span> <span class="st">"Using Smartphone"</span>),</span>
<span id="cb6-12"><a href="#cb6-12"></a>         <span class="at">day =</span> <span class="fu">case_match</span>(day,</span>
<span id="cb6-13"><a href="#cb6-13"></a>                          <span class="st">"wk"</span> <span class="sc">~</span> <span class="st">"Weekdays"</span>,</span>
<span id="cb6-14"><a href="#cb6-14"></a>                          <span class="st">"we"</span> <span class="sc">~</span> <span class="st">"Weekends"</span>))</span>
<span id="cb6-15"><a href="#cb6-15"></a></span>
<span id="cb6-16"><a href="#cb6-16"></a>dat_means <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(wemwbs, screen_long, <span class="at">by =</span> <span class="st">"Serial"</span>) <span class="sc">%&gt;%</span> <span class="co"># Step 4: joining</span></span>
<span id="cb6-17"><a href="#cb6-17"></a>  <span class="co"># Step 5: group_by &amp; summarise</span></span>
<span id="cb6-18"><a href="#cb6-18"></a>  <span class="fu">group_by</span>(technology_type, day, hours) <span class="sc">%&gt;%</span></span>
<span id="cb6-19"><a href="#cb6-19"></a>  <span class="fu">summarise</span>(<span class="at">mean_wellbeing =</span> <span class="fu">mean</span>(WEMWBS_sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'technology_type', 'day'. You can override
using the `.groups` argument.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Now we can plot. There are a few new features in relation to line plots and point shapes. Check them out.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">ggplot</span>(dat_means, <span class="fu">aes</span>(<span class="at">x =</span> hours, <span class="at">y =</span> mean_wellbeing, <span class="at">linetype =</span> day, <span class="at">shape =</span> day)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> technology_type) <span class="sc">+</span> </span>
<span id="cb8-6"><a href="#cb8-6"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span> </span>
<span id="cb8-7"><a href="#cb8-7"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hours of Technology Use"</span>,</span>
<span id="cb8-8"><a href="#cb8-8"></a>       <span class="at">y =</span> <span class="st">"Mean Well-Being Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="11-multiple-regression_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
More info on plot parameters
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>aes <code>linetype</code> changes the type of line, e.g., solid or dotty, and here we specified it to be different for each type of day. More on line types can be found here: <a href="https://sape.inf.usi.ch/quick-reference/ggplot2/linetype.html" target="_blank">https://sape.inf.usi.ch/quick-reference/ggplot2/linetype.html</a>
</li>
<li>to change the shape of the points, we specified <code>shape</code> in the aes, and we defined that it should depend on line of day. However, the point shapes turned into round dots and triangles. Since the original plot suggests dots and squares, we fixed that by adding the <code>scale_shape_manual()</code> function. More on point shapes can be found here: <a href="https://www.sthda.com/english/wiki/ggplot2-point-shapes" target="_blank">https://www.sthda.com/english/wiki/ggplot2-point-shapes</a>
</li>
</ul>
<p>If you are looking really closely, you will notice that the boxes are in a different order and that the x- and y-axes span a bit further. Feel free to fix that yourself.</p>
<p>Also, using facets rather than individual plots means that we have axes labels that span all plots, rather than individual plots we patch together. Plus, the legend is on the side and not within each square. Ah well. Let’s call it a conceptual replication, then, shall we?</p>
</div>
</div>
</div>
</section><section id="activity-5-dataframe-for-the-regression-model" class="level2" data-number="11.5"><h2 data-number="11.5" class="anchored" data-anchor-id="activity-5-dataframe-for-the-regression-model">
<span class="header-section-number">11.5</span> Activity 5: Dataframe for the regression model</h2>
<section id="final-data-wrangling-steps" class="level3" data-number="11.5.1"><h3 data-number="11.5.1" class="anchored" data-anchor-id="final-data-wrangling-steps">
<span class="header-section-number">11.5.1</span> Final data wrangling steps</h3>
<p>Create a new data object that has the mean number of hours per day of smartphone use for each participant, averaged over weekends/weekdays. Because Przybylski and Weinstein’s graph showed that smartphone use of more than 1 hour per day is associated with increasingly negative well-being, we want to filter the data to only include those who use a smart phone for more than one hour per day.</p>
<p>We have done the legwork above when we created <code>screen_long</code>, so we could start from there, or we can go back to our original <code>screentime</code> object. Pick the option that makes most sense to you.</p>
<p>We want to join the wrangled data with well-being, as we did above, but also join with the rest of the participant information, since we need the Gender variable.</p>
<p>Store that output in an object called <code>data_smartphone</code>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints Option 1 (using <code>screen_long</code>)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Step 1: Only include smartphone use and not other technologies.</li>
<li>Step 2: Using <code>screen_long</code>, calculate a mean score of screentime hours for each participant.</li>
<li>Step 3: Only include participants who use a smartphone for more than 1 hour per day.</li>
<li>Step 4: Join the above output with <code>wemwbs</code>, and <code>demo</code>, so that only participants data is shown that have values in all 3 data frames.</li>
<li>Step 5: Select all variables of interest (i.e., <code>Serial</code>, <code>WEMWBS_sum</code>, <code>average_hours</code>, and <code>Gender</code>)</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution Option 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>data_smartphone <span class="ot">&lt;-</span> screen_long <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="co"># Step 1</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">filter</span>(technology_type <span class="sc">==</span> <span class="st">"Using Smartphone"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="co"># Step 2</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">group_by</span>(Serial) <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="fu">summarise</span>(<span class="at">average_hours =</span> <span class="fu">mean</span>(hours)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-7"><a href="#cb9-7"></a>  <span class="co"># Step 3</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>  <span class="fu">filter</span>(average_hours <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-9"><a href="#cb9-9"></a>  <span class="co"># Step 4</span></span>
<span id="cb9-10"><a href="#cb9-10"></a>  <span class="fu">inner_join</span>(wemwbs) <span class="sc">%&gt;%</span> </span>
<span id="cb9-11"><a href="#cb9-11"></a>  <span class="fu">inner_join</span>(demo) <span class="sc">%&gt;%</span> </span>
<span id="cb9-12"><a href="#cb9-12"></a>  <span class="co"># Step 5</span></span>
<span id="cb9-13"><a href="#cb9-13"></a>  <span class="fu">select</span>(Serial, WEMWBS_sum, average_hours, Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(Serial)`
Joining with `by = join_by(Serial)`</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints Option 2 (using <code>screentime</code>)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Step 1: Select all variables from <code>screentime</code> that you need.</li>
<li>Step 2: Calculate a mean score of screentime hours for each participant. You can either do that by pivoting, grouping and summarising (as we usually do), or calculating <code>(col1 +col2)/2</code> to get than average score.</li>
<li>Step 3: Only include participants who use a smartphone for more than 1 hour per day.</li>
<li>Step 4: Join the above output with <code>wemwbs</code>, and <code>demo</code>, so that only participants data is shown that have values in all 3 data frames.</li>
<li>Step 5: Select all variables of interest (i.e., <code>Serial</code>, <code>WEMWBS_sum</code>, <code>average_hours</code>, and <code>Gender</code>)</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution Option 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>data_smartphone <span class="ot">&lt;-</span> screentime <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="co"># Step 1</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">select</span>(Serial, Smart_wk, Smart_we) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4"></a>  <span class="co"># Step 2 - different approach to computing averages</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>  <span class="fu">mutate</span>(<span class="at">average_hours =</span> (Smart_wk <span class="sc">+</span> Smart_we)<span class="sc">/</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-6"><a href="#cb11-6"></a>  <span class="co"># Step 3</span></span>
<span id="cb11-7"><a href="#cb11-7"></a>  <span class="fu">filter</span>(average_hours <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-8"><a href="#cb11-8"></a>  <span class="co"># Step 4</span></span>
<span id="cb11-9"><a href="#cb11-9"></a>  <span class="fu">inner_join</span>(wemwbs) <span class="sc">%&gt;%</span> </span>
<span id="cb11-10"><a href="#cb11-10"></a>  <span class="fu">inner_join</span>(demo) <span class="sc">%&gt;%</span> </span>
<span id="cb11-11"><a href="#cb11-11"></a>  <span class="co"># Step 5</span></span>
<span id="cb11-12"><a href="#cb11-12"></a>  <span class="fu">select</span>(Serial, WEMWBS_sum, average_hours, Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(Serial)`
Joining with `by = join_by(Serial)`</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="mean-centering-variables" class="level3" data-number="11.5.2"><h3 data-number="11.5.2" class="anchored" data-anchor-id="mean-centering-variables">
<span class="header-section-number">11.5.2</span> Mean-centering variables</h3>
<p>As you have seen in the lectures, when you have continuous variables in a regression model, it is often sensible to transform them by <strong>mean centering</strong>. You mean center a predictor <code>X</code> by subtracting the mean of the predictor (<code>X_centered = X - mean(X)</code>) or you can use the <code><a href="https://rdrr.io/r/base/scale.html">scale()</a></code> function. This has two useful consequences:</p>
<ul>
<li><p>The model intercept represents the predicted value of <span class="math inline">\(Y\)</span> when the predictor variable is at its mean, rather than at zero in the unscaled version.</p></li>
<li><p>When interactions are included in the model, significant effects can be interpreted as the overall effect of a predictor on the outcome (i.e., a main effect) rather than its effect at a specific level of another predictor (i.e., a simple effect).</p></li>
</ul>
<p>For categorical predictors with two levels, these become coded as -.5 and .5 (because the mean of these two values is 0). This is also known as deviation coding.</p>
<p>If we used dummy coding (i.e., leaving the categorical predictor as 0 and 1) instead of deviation coding, the interpretation would change slightly:</p>
<ul>
<li>
<strong>Dummy-coding interpretation</strong>: The intercept represents the predicted outcome for the reference group (coded as 0), and the coefficient for the categorical predictor represents the difference in the outcome between the two groups.</li>
<li>
<strong>Deviation-coding interpretation</strong>: The intercept represents the overall mean outcome across both groups, and the coefficient for the categorical predictor represents the average difference between the two groups, centered around zero.</li>
</ul>
<p>Use <code>mutate()</code> to add two new variables to <code>data_smartphone</code>:</p>
<ul>
<li>
<code>average_hours_centered</code>: calculated as a mean-centered version of the <code>total_hours</code> predictor</li>
<li>
<code>gender_recoded</code>: recode Gender .5 for “Male” and -.5 for “Female or unknown”.</li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>data_smartphone <span class="ot">&lt;-</span> data_smartphone <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">mutate</span>(<span class="at">average_hours_centered =</span> average_hours <span class="sc">-</span> <span class="fu">mean</span>(average_hours),</span>
<span id="cb13-3"><a href="#cb13-3"></a>         <span class="co">#alternative with the scale function: </span></span>
<span id="cb13-4"><a href="#cb13-4"></a>         <span class="co">#average_hours_centered = scale(average_hours, scale = FALSE),</span></span>
<span id="cb13-5"><a href="#cb13-5"></a>         <span class="at">gender_recoded =</span> <span class="fu">case_match</span>(Gender,</span>
<span id="cb13-6"><a href="#cb13-6"></a>                                     <span class="st">"Male"</span>  <span class="sc">~</span> <span class="fl">0.5</span>,</span>
<span id="cb13-7"><a href="#cb13-7"></a>                                     <span class="st">"Female or unknown"</span> <span class="sc">~</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb13-8"><a href="#cb13-8"></a>         <span class="at">gender_recoded =</span> <span class="fu">factor</span>(gender_recoded),</span>
<span id="cb13-9"><a href="#cb13-9"></a>         <span class="at">Gender =</span> <span class="fu">factor</span>(Gender))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="activity-6-compute-the-regression-confidence-intervals-and-effect-size" class="level2" data-number="11.6"><h2 data-number="11.6" class="anchored" data-anchor-id="activity-6-compute-the-regression-confidence-intervals-and-effect-size">
<span class="header-section-number">11.6</span> Activity 6: Compute the regression, confidence intervals, and effect size</h2>
<p>For the data in <code>smart_wb</code>, use the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function to calculate the multiple regression model:</p>
<p><span class="math inline">\(Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i} + e_i\)</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(Y_i\)</span> is the well-being score for participant <span class="math inline">\(i\)</span>;</p></li>
<li><p><span class="math inline">\(X_{1i}\)</span> is the mean-centered smartphone use variable for participant <span class="math inline">\(i\)</span>;</p></li>
<li><p><span class="math inline">\(X_{2i}\)</span> is gender (-.5 = female, .5 = male);</p></li>
<li><p><span class="math inline">\(X_{3i}\)</span> is the interaction between smartphone use and gender (<span class="math inline">\(= X_{1i} \times X_{2i}\)</span>)</p></li>
</ul>
<p>In R terms, this translate to the following format:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">lm</span>(OutcomeVariable <span class="sc">~</span> PredictorVariable1 <span class="sc">+</span> PredictorVariable2 <span class="sc">+</span> Interaction, data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The code <code>lm(OutcomeVariable ~ PredictorVariable1 + PredictorVariable2, data)</code> will add predictors 1 and 2. This will provide you with the contributions of each predictor to explain the outcome variable, i.e.&nbsp;main effects only.</p>
<p>However, if you are also interested in the interaction between the two predictors, then you would:</p>
<ul>
<li>use a <code>*</code> instead of a <code>+</code>: <code>lm(OutcomeVariable ~ PredictorVariable1 * PredictorVariable2, data)</code> for the model to include 2 main effects and the interaction. OR</li>
<li>use the longer format and add the interaction term manually <code>lm(OutcomeVariable ~ PredictorVariable1 + PredictorVariable2 + PredictorVariable1:PredictorVariable2, data)</code>. Notice the colon <code>:</code>
</li>
</ul>
</div>
</div>
<p>::: {.callout-note icon=“false”}</p>
</section><section id="your-turn" class="level2" data-number="11.7"><h2 data-number="11.7" class="anchored" data-anchor-id="your-turn">
<span class="header-section-number">11.7</span> Your Turn</h2>
<ul>
<li>Save your model to the object <code>mod</code>.</li>
<li>Run the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> of your model to see the output of the regression.</li>
<li>Compute confidence intervals</li>
<li>Compute the effect size <span class="math inline">\(f^2\)</span>
</li>
</ul>
<p>These are the exact same functions as last time, except for the model including more variables.</p>
<p>Answer the following questions:</p>
<ul>
<li><p>The interaction between smartphone use and gender is shown by the variable <select class="webex-select"><option value="blank"></option>
<option value="x">average_hours_centered</option>
<option value="x">gender_recoded0.5</option>
<option value="answer">average_hours_centered:gender_recoded0.5</option></select>, and this interaction was <select class="webex-select"><option value="blank"></option>
<option value="answer">significant</option>
<option value="x">non-significant</option></select> at the <span class="math inline">\(\alpha = .05\)</span> level.</p></li>
<li><p>To 2 decimal places, adjusted <span class="math inline">\(R^2\)</span> suggests the overall model explains what percentage of the variance in well-being scores? <input class="webex-solveme nospaces" size="4" data-answer="[&quot;9.38&quot;]"></p></li>
<li><p>The <em>p</em>-value for the overall model fit is <code>&lt;2e-16</code>. Is this statistically significant? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>. How would you note that p-value in APA style when writing up the results? <input class="webex-solveme nospaces" size="8" data-answer="[&quot;p<.001&quot;,&quot;p < .001&quot;]"></p></li>
<li><p>What is the observed effect size (in <span class="math inline">\(f^2\)</span>) for the study to 3 decimal places? <input class="webex-solveme nospaces" data-tol="0.001" size="5" data-answer="[&quot;0.103&quot;,&quot;.103&quot;]"></p></li>
</ul>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="do">## model</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> WEMWBS_sum <span class="sc">~</span> average_hours_centered <span class="sc">*</span> gender_recoded, </span>
<span id="cb15-3"><a href="#cb15-3"></a>               <span class="at">data =</span> data_smartphone)</span>
<span id="cb15-4"><a href="#cb15-4"></a></span>
<span id="cb15-5"><a href="#cb15-5"></a><span class="do">## regression output</span></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="fu">summary</span>(mod)</span>
<span id="cb15-7"><a href="#cb15-7"></a></span>
<span id="cb15-8"><a href="#cb15-8"></a><span class="do">## confidence intervals</span></span>
<span id="cb15-9"><a href="#cb15-9"></a><span class="fu">confint</span>(mod)</span>
<span id="cb15-10"><a href="#cb15-10"></a></span>
<span id="cb15-11"><a href="#cb15-11"></a><span class="do">## effect size</span></span>
<span id="cb15-12"><a href="#cb15-12"></a>r_sq_adj <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod)<span class="sc">$</span>adj.r.squared</span>
<span id="cb15-13"><a href="#cb15-13"></a>f_2 <span class="ot">&lt;-</span> r_sq_adj<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>r_sq_adj)</span>
<span id="cb15-14"><a href="#cb15-14"></a>f_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WEMWBS_sum ~ average_hours_centered * gender_recoded, 
    data = data_smartphone)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.881  -5.721   0.408   6.237  27.264 

Coefficients:
                                         Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                              44.86740    0.04478 1001.87   &lt;2e-16
average_hours_centered                   -0.77121    0.02340  -32.96   &lt;2e-16
gender_recoded0.5                         5.13968    0.07113   72.25   &lt;2e-16
average_hours_centered:gender_recoded0.5  0.45205    0.03693   12.24   &lt;2e-16
                                            
(Intercept)                              ***
average_hours_centered                   ***
gender_recoded0.5                        ***
average_hours_centered:gender_recoded0.5 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.135 on 71029 degrees of freedom
Multiple R-squared:  0.09381,   Adjusted R-squared:  0.09377 
F-statistic:  2451 on 3 and 71029 DF,  p-value: &lt; 2.2e-16

                                              2.5 %     97.5 %
(Intercept)                              44.7796275 44.9551788
average_hours_centered                   -0.8170719 -0.7253385
gender_recoded0.5                         5.0002576  5.2791028
average_hours_centered:gender_recoded0.5  0.3796615  0.5244376
[1] 0.1034697</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-7-visualising-interactions" class="level2" data-number="11.8"><h2 data-number="11.8" class="anchored" data-anchor-id="activity-7-visualising-interactions">
<span class="header-section-number">11.8</span> Activity 7: Visualising interactions</h2>
<p>It is very difficult to understand an interaction from the coefficient alone, so your best bet is visualising the interaction to help you understand the results and communicate your results to your readers.</p>
<p>There is a great package called <code>sjPlot</code> which takes regression models and helps you plot them in different ways. We will demonstrate plotting interactions, but for further information and options, see the <a href="https://strengejacke.github.io/sjPlot/articles/plot_interactions.html" target="_blank">online documentation</a>.</p>
<p>To plot the interaction, you need the model object (not the summary), specify “pred” as the <code>type</code> as we want to plot predictions, and add the <code>terms</code> you want to plot.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">plot_model</span>(mod, </span>
<span id="cb17-2"><a href="#cb17-2"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb17-3"><a href="#cb17-3"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"average_hours_centered"</span>, <span class="st">"gender_recoded"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="11-multiple-regression_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>What is the most reasonable interpretation of the interaction?</p>
<div id="radio_QMUVAUHYZL" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_QMUVAUHYZL" value="x"><span>smartphone use harms boys more than girls</span></label><label><input type="radio" autocomplete="off" name="radio_QMUVAUHYZL" value="x"><span>there is no evidence for gender differences in the relationship between smartphone use and well-being</span></label><label><input type="radio" autocomplete="off" name="radio_QMUVAUHYZL" value="answer"><span>smartphone use was more negatively associated with wellbeing for girls than for boys</span></label><label><input type="radio" autocomplete="off" name="radio_QMUVAUHYZL" value="x"><span>smartphone use harms girls more than boys</span></label>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>plot_model()</code> uses <code>ggplot2</code> in the background. You can add further customisation by adding layers after the initial function. You can also use <code>ggsave()</code> to save your plots and insert them into your work.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example of a more tidy plot
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For example, we can tidy up the axis labels and remove the title, and set a theme.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">plot_model</span>(mod, </span>
<span id="cb18-2"><a href="#cb18-2"></a>           <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb18-3"><a href="#cb18-3"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"average_hours_centered"</span>, <span class="st">"gender_recoded"</span>)) <span class="sc">+</span> </span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Total Hours Smartphone Use"</span>,</span>
<span id="cb18-5"><a href="#cb18-5"></a>       <span class="at">y =</span> <span class="st">"Total Well-Being Score"</span>,</span>
<span id="cb18-6"><a href="#cb18-6"></a>       <span class="at">title =</span> <span class="st">""</span>) <span class="sc">+</span> </span>
<span id="cb18-7"><a href="#cb18-7"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="11-multiple-regression_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="activity-8-check-assumptions" class="level2" data-number="11.9"><h2 data-number="11.9" class="anchored" data-anchor-id="activity-8-check-assumptions">
<span class="header-section-number">11.9</span> Activity 8: Check assumptions</h2>
<p>Now it’s time to test those pesky assumptions. The assumptions for multiple regression are the same as simple regression but there is one additional assumption, that of multicollinearity. This is the idea that predictor variables should not be too highly correlated.</p>
<p>Assumptions are:</p>
<ol type="1">
<li>The outcome/DV is a interval/ratio level data, and the predictor variable is interval/ratio or categorical (with two levels).</li>
<li>All values of the outcome variable are independent (i.e., each score should come from a different participant).</li>
<li>The predictors have non-zero variance.</li>
<li>The relationship between outcome and predictor is linear.</li>
<li>The residuals should be normally distributed.</li>
<li>There should be homoscedasticity (homogeneity of variance, but for the residuals).</li>
<li>Multicollinearity: predictor variables should not be too highly correlated.</li>
</ol>
<p>We can use the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> function for diagnostic plots or the <code>check_model()</code> from the <code>performance</code> package.</p>
<p>One difference from when we used <code>check_model()</code> previously is that rather than just letting it run all the tests it wants, we are going to specify which tests to stop it throwing an error.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A word of warning - these assumption tests will take longer than usual to run because it’s such a big data set.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">check_model</span>(mod, </span>
<span id="cb19-2"><a href="#cb19-2"></a>            <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"vif"</span>, </span>
<span id="cb19-3"><a href="#cb19-3"></a>                      <span class="st">"qq"</span>, </span>
<span id="cb19-4"><a href="#cb19-4"></a>                      <span class="st">"normality"</span>, </span>
<span id="cb19-5"><a href="#cb19-5"></a>                      <span class="st">"linearity"</span>, </span>
<span id="cb19-6"><a href="#cb19-6"></a>                      <span class="st">"homogeneity"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="11-multiple-regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="assumptions-1-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumptions-1-3">Assumptions 1-3</h4>
<p>From the work we have done so far, we know that we meet assumptions 1-3.</p>
</section><section id="assumption-4-linearity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-4-linearity">Assumption 4: Linearity</h4>
<p>We already know from looking at the scatterplot that the relationship is linear, but the residual plot also confirms this.</p>
</section><section id="assumption-5-normality-of-residuals" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-5-normality-of-residuals">Assumption 5: Normality of residuals</h4>
<p>The residuals look good in both plots and this provides an excellent example of why it’s often better to visualise than rely on statistics. With a sample size this large, any statistical diagnostic tests will be highly significant as they are sensitive to sample size.</p>
</section><section id="assumption-6-homoscedasticity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-6-homoscedasticity">Assumption 6: Homoscedasticity</h4>
<p>The plot is missing the reference line. Fun fact, this took us several days of our lives and asking for help on social media to figure out. The reason the line is not there is because the data set is so large that is creates a memory issue. However, if you use the <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> version, it does show the reference line.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">plot</span>(mod, <span class="at">which =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="11-multiple-regression_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>It is not perfect, but the reference line is roughly flat to suggest there are no serious issues with homoscedasticity.</p>
</section><section id="assumption-7-multicollinearity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-7-multicollinearity">Assumption 7: Multicollinearity</h4>
<p>From the collinearity plot, we can see that both main effects and the interaction term are in the “green zone” which is great. Howeverm we can also test this statistically using <code>check_collinearity()</code> to produce VIF (variance inflation factor) and tolerance values.</p>
<p>Essentially, this function estimates how much the variance of a coefficient is “inflated” because of linear dependence with other predictors, i.e., that a predictor is not actually adding any unique variance to the model, it’s just really strongly related to other predictors. <a href="https://statisticalhorizons.com/multicollinearity" target="_blank">You can read more about this online</a>. Thankfully, VIF is not affected by large samples like other statistical diagnostic tests.</p>
<p>There are various rules of thumb, but most converge on a <strong>VIF of above 2 - 2.5</strong> for any one predictor to be problematic. Here we are well under 2 for all 3 terms of the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">check_collinearity</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">VIF</th>
<th style="text-align: right;">VIF_CI_low</th>
<th style="text-align: right;">VIF_CI_high</th>
<th style="text-align: right;">SE_factor</th>
<th style="text-align: right;">Tolerance</th>
<th style="text-align: right;">Tolerance_CI_low</th>
<th style="text-align: right;">Tolerance_CI_high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">average_hours_centered</td>
<td style="text-align: right;">1.721968</td>
<td style="text-align: right;">1.704219</td>
<td style="text-align: right;">1.740165</td>
<td style="text-align: right;">1.312238</td>
<td style="text-align: right;">0.5807308</td>
<td style="text-align: right;">0.5746582</td>
<td style="text-align: right;">0.5867789</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_recoded</td>
<td style="text-align: right;">1.035552</td>
<td style="text-align: right;">1.028488</td>
<td style="text-align: right;">1.044369</td>
<td style="text-align: right;">1.017621</td>
<td style="text-align: right;">0.9656682</td>
<td style="text-align: right;">0.9575159</td>
<td style="text-align: right;">0.9723014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">average_hours_centered:gender_recoded</td>
<td style="text-align: right;">1.716349</td>
<td style="text-align: right;">1.698683</td>
<td style="text-align: right;">1.734463</td>
<td style="text-align: right;">1.310095</td>
<td style="text-align: right;">0.5826319</td>
<td style="text-align: right;">0.5765474</td>
<td style="text-align: right;">0.5886915</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section></section><section id="activity-9-sensitivity-power-analysis" class="level2" data-number="11.10"><h2 data-number="11.10" class="anchored" data-anchor-id="activity-9-sensitivity-power-analysis">
<span class="header-section-number">11.10</span> Activity 9: Sensitivity power analysis</h2>
<p>As usual, we want to calculate the smallest effect size that our study was able to detect, given our design and sample size.</p>
<p>To do this, we use the <code>pwr.f2.test()</code> function from the <code>pwr</code> package. This is the same as in chapter 10 for simple linear regression. Remember the arguments for this function:</p>
<ul>
<li>
<code>u</code> = Numerator degrees of freedom. This the number of coefficients you have in your model (minus the intercept)</li>
<li>
<code>v</code> = Denominator degrees of freedom. This is calculated as <span class="math inline">\(v=n-u-1\)</span>, where <span class="math inline">\(n\)</span> is the number of participants.</li>
<li>
<code>f2</code> = The effect size. Here we are solving the effect size, so this parameter is left out</li>
<li>
<code>sig.level</code> = The significance level of your study. This is usually set to 0.05</li>
<li>
<code>power</code> = The power level of your study. This is usually set to 0.8, but let’s go for 0.99 this time (just because we have such a large number of participants)</li>
</ul>
<p>Run the sensitivity power analysis and then answer the following questions:</p>
<ul>
<li>To 3 decimal places, what is the smallest effect size that this study could reliably detect? <input class="webex-solveme nospaces" data-tol="0.01" size="0.000" data-answer="[&quot;.000&quot;]">
</li>
</ul>
<p>Since the observed effect size from our inferential statistics was <select class="webex-select"><option value="blank"></option>
<option value="x">smaller</option>
<option value="answer">larger</option></select> than the effect you could reliably detect with this design, the test was <select class="webex-select"><option value="blank"></option>
<option value="answer">sufficiently powered</option>
<option value="">underpowered</option></select> to detect the observed effect.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">pwr.f2.test</span>(<span class="at">u =</span> <span class="dv">3</span>, <span class="at">v =</span> <span class="dv">71029</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Multiple regression power calculation 

              u = 3
              v = 71029
             f2 = 0.0003673651
      sig.level = 0.05
          power = 0.99</code></pre>
</div>
</div>
<p>The study was incredibly sensitive, where they would detect effects of <span class="math inline">\(f^2 = .0004\)</span> with 99% power. Needless to say, this study was sufficiently powered.</p>
</div>
</div>
</div>
</section><section id="activity-10-the-write-up" class="level2" data-number="11.11"><h2 data-number="11.11" class="anchored" data-anchor-id="activity-10-the-write-up">
<span class="header-section-number">11.11</span> Activity 10: The write-up</h2>
<p>All continuous predictors were mean-centered and deviation coding was used for categorical predictors. The results of the regression indicated that the model significantly predicted wellbeing <span class="math inline">\((F(3, 71029) = 2451, p &lt; .001, R^2_{Adjusted} = .094, f^2 = .103)\)</span>, accounting for 9.4% of the variance. Total screen time was a significant negative predictor of wellbeing scores <span class="math inline">\((\beta = -0.77, 95\% CI = [-0.82, -0.73], p &lt; .001\)</span>), as was gender <span class="math inline">\((\beta = 5.14, p &lt; .001\)</span>), with girls having lower wellbeing scores than boys. Importantly, there was a significant interaction between screen time and gender <span class="math inline">\((\beta = 0.45, 95\% CI = [0.38, 0.52], p &lt; .001\)</span>), meaning that smartphone use was more negatively associated with well-being for girls than for boys.</p>
</section><section id="pair-coding" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="pair-coding"><span style="color: #F39C12; text-transform: uppercase;">Pair-coding</span></h2>
<p><em>to be added</em></p>
</section><section id="test-your-knowledge" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="test-your-knowledge"><span style="color: #F39C12; text-transform: uppercase;">Test your knowledge</span></h2>
<p><em>to be added</em></p>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./10-regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12-one-way-anova.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">CC-BY (2024) Gaby Mahrholz</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>